@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

skinparam rectangle {
        BackgroundColor<<PLACEHOLDER>> transparent
        BorderThickness<<PLACEHOLDER>> .1
        BorderColor<<PLACEHOLDER>> transparent
              FontColor<<PLACEHOLDER>> transparent
               FontSize<<PLACEHOLDER>> 0
    StereotypeFontColor<<PLACEHOLDER>> transparent
     StereotypeFontSize<<PLACEHOLDER>> 0
Shadowing<<PLACEHOLDER>> false
}

rectangle a <<PLACEHOLDER>> {
}

frame timetable {

Component [Timetable] TIMETABLE_COLOR
Component [TimetableItem] TIMETABLE_COLOR
Component [TimetableLesson] TIMETABLE_COLOR
Component [TimetableUserItem] TIMETABLE_COLOR

[TimetableLesson] --> TimetableItem
[TimetableUserItem] --> TimetableItem
Logic--> [Timetable]
[Storage] --> [Timetable]
[Timetable] --> UI
}


frame [Logic] LOGIC_COLOR {
}

frame [Storage] STORAGE_COLOR {
}

frame [UI] UI_COLOR {
}

@enduml