@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

skinparam rectangle {
        BackgroundColor<<PLACEHOLDER>> transparent
        BorderThickness<<PLACEHOLDER>> .1
        BorderColor<<PLACEHOLDER>> transparent
              FontColor<<PLACEHOLDER>> transparent
               FontSize<<PLACEHOLDER>> 0
    StereotypeFontColor<<PLACEHOLDER>> transparent
     StereotypeFontSize<<PLACEHOLDER>> 0
Shadowing<<PLACEHOLDER>> false
}

rectangle a <<PLACEHOLDER>> {
}

frame Timetable {

Component [Timetable] TIMETABLE_COLOR
Component [TimetableDto] TIMETABLE_COLOR
Component [TimetableItem] TIMETABLE_COLOR
Component [TimetableUserItem] TIMETABLE_COLOR

}


frame [UniMods] UNIMODS_COLOR {
}

frame [Logic] LOGIC_COLOR {
}

frame [Storage] STORAGE_COLOR {
}

frame [Online] ONLINE_COLOR {
}

frame [UI] UI_COLOR {
}

@enduml