@startuml

[-> WeeksAdapterFactory : create()
activate WeeksAdapterFactory

WeeksAdapterFactory -> WeeksAdapter** : create()
activate WeeksAdapter


alt weeks != null
    WeeksAdapter -> WeeksAdapter : writeAsIntArray()
    activate WeeksAdapter
    WeeksAdapter --> WeeksAdapter
    deactivate WeeksAdapter
else else
    WeeksAdapter -> WeeksAdapter : writeAsObject()
    activate WeeksAdapter
    WeeksAdapter --> WeeksAdapter
    deactivate WeeksAdapter
end

WeeksAdapter --> WeeksAdapterFactory
deactivate WeeksAdapter
destroy WeeksAdapter

<-- WeeksAdapterFactory
deactivate WeeksAdapterFactory

@enduml
