@startuml
class seedu.duke.command.GraphCommand {
- {static} Ui ui
+ void execute(ArrayList<String>)
}
class seedu.duke.exceptions.FoodoramaException {
}


seedu.duke.command.Command <|-- seedu.duke.command.GraphCommand
seedu.duke.exceptions.Exception <|-- seedu.duke.exceptions.FoodoramaException
@enduml