@startuml
'https://plantuml.com/class-diagram

together {
package "Command" {
class CommandResult #pink ##red {
feedbackToUser: String
itemList: ArrayList
map: Map<String, ArrayList>
}
abstract class Command #pink ##red {
workoutMode: int {static}
}
}
}

package "Ui" {
class Ui {
withIndent: boolean
showResultToUser(result: CommandResult):void()
printErrorMessage(e: GetJackDException):void()
printWelcomeMessage():void() {static}
}
}

CommandResult   ---|>    Ui: result
Command ---|> Ui

@enduml