@startuml
skinparam classAttributeIconSize 0
skinparam shadowing false
hide circle
hide empty members

together {
package "Command" {
class CommandResult #Orange {
feedbackToUser: String
itemList: ArrayList
map: Map<String, ArrayList>
}
abstract class "{abstract} \n Command" as Command #Orange {
workoutMode: int {static}
}
}
}

package "Ui" {
class Ui #White ##Black {
withIndent: boolean
showResultToUser(result: CommandResult):void()
printErrorMessage(e: GetJackDException):void()
printWelcomeMessage():void() {static}
}
}

Ui ..> CommandResult
Ui ..> Command
@enduml