@startuml
!include Style.puml
Actor User
participant ":Parser"
User -> ":Parser" : "help"
activate ":Parser"
create ":HelpCommand"
":Parser" -> ":HelpCommand" : HelpCommand()
":Parser" -> ":HelpCommand" : execute()
activate ":HelpCommand"

deactivate ":Parser"
":HelpCommand" -> "<<class>>\n:ClassPackageReader" : getCommandsAndPrintSyntax()
"<<class>>\n:ClassPackageReader" -> ":Command" : getSyntax()
":HelpCommand" --> ":Parser"
deactivate ":HelpCommand"
":Command" --> "<<class>>\n:ClassPackageReader" : syntax
"<<class>>\n:ClassPackageReader" --> User : Prints help messages
destroy ":HelpCommand"

@enduml