@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User as Foo
Foo -> Click: "zoom add CS2113T https://nus-sg.com"
activate Click

Click -> Parser: parseCommand()
activate Parser

create AddZoomCommand
Parser -> AddZoomCommand: new AddZoomCommand()
activate AddZoomCommand

Parser <-- AddZoomCommand
deactivate AddZoomCommand

Click <-- Parser
deactivate Parser

Click --> AddZoomCommand: execute()
activate AddZoomCommand

AddZoomCommand -> StorageZoom: saveLink()
activate StorageZoom

StorageZoom -> Ui: printMessage()
activate Ui

StorageZoom <-- Ui
deactivate Ui

AddZoomCommand <-- StorageZoom
deactivate StorageZoom

Click <-- AddZoomCommand
deactivate AddZoomCommand
destroy AddZoomCommand

Foo <-- Click
deactivate Click

@enduml