@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User as Foo
Foo -> Click: "zoom list"
activate Click

Click -> Parser: parseCommand()
activate Parser

create ListZoomLinksCommand
Parser -> ListZoomLinksCommand: new ListZoomLinksCommand()
activate ListZoomLinksCommand

Parser <-- ListZoomLinksCommand
deactivate ListZoomLinksCommand

Click <-- Parser
deactivate Parser

Click --> ListZoomLinksCommand: execute()
activate ListZoomLinksCommand

ListZoomLinksCommand -> StorageZoom: displayLinks()
activate StorageZoom

StorageZoom -> Ui: displayZoomLink()
activate Ui

StorageZoom <-- Ui
deactivate Ui

ListZoomLinksCommand <-- StorageZoom
deactivate StorageZoom

Click <-- ListZoomLinksCommand
deactivate ListZoomLinksCommand
destroy ListZoomLinksCommand

Foo <-- Click
deactivate Click


@enduml