@startuml
'https://plantuml.com/sequence-diagram

participant ":AddModuleCommand" as AddModuleCommand
participant ":ModuleStorage" as ModuleStorage

-> AddModuleCommand : execute(ui, moduleManager)
activate AddModuleCommand
  group ref [Refer to Add Module Section]
    |||
  end
    |||
  AddModuleCommand -> ModuleStorage : getInstance()
  activate ModuleStorage
    |||
    return ":ModuleStorage"
  Deactivate ModuleStorage
  AddModuleCommand -> ModuleStorage : createModuleDirectory()






@enduml