@startuml
'https://plantuml.com/sequence-diagram

!include ../SequenceStyle.puml

box Main TERMINUS_BOX_COLOR
participant ":Terminus" as Terminus TERMINUS_COLOR
endbox

box Storage STORAGE_BOX_COLOR
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":Storage" as Storage STORAGE_COLOR
participant ":JsonStorage" as JsonStorage STORAGE_COLOR
endbox

activate Terminus
Terminus -> StorageManager : initialise()
activate StorageManager
Create Storage
  StorageManager -> Storage : Storage()
  activate Storage
return storage
StorageManager -> Storage : createFolder(:Path)
activate Storage
|||
return
StorageManager -> JsonStorage : execute(null : ModuleManager, CREATE : StorageActionEnum)
activate JsonStorage
note left: Create data folder and \nmain json file \nif they do not exists
  JsonStorage -> JsonStorage : createJson()
  activate JsonStorage
  JsonStorage -> JsonStorage : createFolder(:Path)
  activate JsonStorage
  return
  JsonStorage -> JsonStorage : createFile(:Path)
  activate JsonStorage
  return
return
return
ref over StorageManager
  load
end
return moduleManager
destroy Storage


@enduml