@startuml
'https://plantuml.com/sequence-diagram

box Terminus #whitesmoke
participant ":Terminus" as Terminus #white
endbox

box Storage #lightpink
participant ":StorageManager" as StorageManager #mistyrose
participant ":JsonStorage" as JsonStorage #mistyrose
participant ":NoteStorage" as NoteStorage #mistyrose
participant ":PdfStorage" as PdfStorage #mistyrose
participant ":FolderStorage" as FolderStorage #mistyrose
endbox

-> Terminus : initialize()
activate Terminus

create StorageManager
  Terminus -> StorageManager : StorageManager(:Path, :String)
  activate StorageManager
    create JsonStorage
      StorageManager -> JsonStorage : JsonStorage(:Path, :String)
      activate JsonStorage
    return jsonStorage
    create NoteStorage
      StorageManager -> NoteStorage : NoteStorage(:Path)
      activate NoteStorage
    return noteStorage
    create PdfStorage
      StorageManager -> PdfStorage : PdfStorage(:Path)
      activate PdfStorage
    return pdfStorage
    create FolderStorage
      StorageManager -> FolderStorage : FolderStorage(:Path)
      activate FolderStorage
    return folderStorage
  return storageManager
|||

@enduml