@startuml
'https://plantuml.com/sequence-diagram

participant ":Terminus" as Terminus
participant ":StorageManager" as StorageManager

participant ":JsonStorage" as JsonStorage
participant ":NoteStorage" as NoteStorage
participant ":PdfStorage" as PdfStorage
participant ":FolderStorage" as FolderStorage


-> Terminus : initialize()
activate Terminus

create StorageManager
  Terminus -> StorageManager : StorageManager(:Path, :String)
  activate StorageManager
    create JsonStorage
      StorageManager -> JsonStorage : JsonStorage(:Path, :String)
      activate JsonStorage
    return jsonStorage
    create NoteStorage
      StorageManager -> NoteStorage : NoteStorage(:Path)
      activate NoteStorage
    return noteStorage
    create PdfStorage
      StorageManager -> PdfStorage : PdfStorage(:Path)
      activate PdfStorage
    return pdfStorage
    create FolderStorage
      StorageManager -> FolderStorage : FolderStorage(:Path)
      activate FolderStorage
    return folderStorage
  return storageManager
|||

@enduml