@startuml
'https://plantuml.com/sequence-diagram

mainframe sd load

box Storage #lightpink
participant ":StorageManager" as StorageManager #mistyrose
participant ":JsonStorage" as JsonStorage #mistyrose
participant ":FilterManager" as FilterManager #mistyrose
participant ":NoteStorage" as NoteStorage #mistyrose
endbox

activate StorageManager
StorageManager -> StorageManager : load()
activate StorageManager
StorageManager -> JsonStorage : loadJson()
activate JsonStorage
return moduleManager
opt moduleManager is null
<-- StorageManager : ModuleManager()
end
create FilterManager
StorageManager -> FilterManager : FilterManager()
activate FilterManager
return filterManager
StorageManager -> FilterManager : filter(:ModuleStorage)
note left : Remove any \ninvalid data \nin ModuleManager \nloaded from json
activate FilterManager
return
destroy FilterManager
loop each module in ModuleManager
  StorageManager -> NoteStorage : execute(:ModuleManager, module : String, null : String, RELOAD : StorageActionEnum)
  activate NoteStorage
  note left : ignore the file \nif exception \nis caught
  |||
  note right: Load Note data \ninto ModuleManager
  return
end
return moduleManager





@enduml