@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceMessageAlign center

box Terminus #whitesmoke
participant ":Terminus" as Terminus #white
endbox

box Storage #lightpink
participant ":StorageManager" as StorageManager #mistyrose
participant ":Storage" as Storage #mistyrose
participant ":JsonStorage" as JsonStorage #mistyrose
endbox

activate Terminus
Terminus -> StorageManager : initialise()
activate StorageManager
Create Storage
  StorageManager -> Storage : Storage()
  activate Storage
return storage
StorageManager -> Storage : createFolder(:Path)
activate Storage
|||
return
destroy Storage
StorageManager -> JsonStorage : execute(null : ModuleManager, CREATE : StorageActionEnum)
activate JsonStorage
note left: Create data folder and \nmain json file \nif they do not exists
  JsonStorage -> JsonStorage : createJson()
  activate JsonStorage
  JsonStorage -> JsonStorage : createFolder(:Path)
  activate JsonStorage
  return
  JsonStorage -> JsonStorage : createFile(:Path)
  activate JsonStorage
  return
return
return
ref over StorageManager
  load
end
return moduleManager


@enduml