@startuml
'https://plantuml.com/sequence-diagram


skinparam sequenceMessageAlign center

box Command #thistle
participant ":DeleteCommand" as DeleteCommand #violet
endbox

box Content #goldenrod
participant ":ContentManager" as ContentManager #gold
participant ":Content" as Content #gold
endbox

-> DeleteCommand : execute()
activate DeleteCommand
DeleteCommand -> ContentManager : deleteContent(contentNumber:int)
activate ContentManager
ContentManager -> ContentManager : isNotValidNumber(:int)
activate ContentManager
note left : Invalid contentNumber: \ncontentNumber < 1 and \ncontentNumber > the size of arraylist
return
alt contentNumber is not valid
ContentManager --> DeleteCommand : InvalidArgumentException()
else else
ContentManager -> Content : getName()
activate Content
return
note left : Remove the Content from \nthe arraylist of Content \nin ContentManager.
destroy Content
end
return deletedContentName:String
return :CommandResult

@enduml