@startuml
!include ObjectStyle.puml

class ClassList
class TeachingClass {
    id = CS2113T-F12
}
class AssessmentList
class Assessment {
    name = Midterms
    maximumMarks = 100
    weightage = 10
}
class StudentList
class Student {
    id = A0123456Z
    name = Student
    comment = Good
    results = <Midterms, 60.00>
}


ClassList *-> TeachingClass
TeachingClass *-down-> "1" StudentList
StudentList *-down-> Student
TeachingClass *-down-> "1" AssessmentList
AssessmentList *-down-> Assessment

@enduml