package seedu.typists.content;

public class Books {
    private static String[] bookContent = {
        "A green hunting "
                + "cap squeezed the top of the fleshy "
                + "balloon of a head. The green earflaps, "
                + "full of large ears and uncut hair and the fine "
                + "bristles that grew in the ears themselves, "
                + "stuck out on either side like turn signals "
                + "indicating two directions at once. "
                + "Full, pursed lips protruded beneath the bushy black "
                + "moustache and, at their corners, sank into little folds "
                + "filled with disapproval and potato chip crumbs. "
                + "In the shadow under the green visor of the cap Ignatius J. "
                + "Reilly’s supercilious blue and yellow eyes looked down "
                + "upon the other people waiting under the clock at the D.H. "
                + "Holmes department store, studying the crowd of "
                + "people for signs of bad taste in dress. "
                + "Several of the outfits, Ignatius noticed, "
                + "were new enough and expensive enough to be properly "
                + "considered offenses against taste and decency. "
                + "Possession of anything new or expensive only reflected a "
                + "person’s lack of theology and geometry;"
                + "it could even cast doubts upon one’s soul.",
        "Call me Ishmael. "
                + "Some years ago - never mind how long precisely - "
                + "having little or no money in my purse, "
                + "and nothing particular to interest me on shore, "
                + "I thought I would sail about "
                + "a little and see the watery part of the world. It is a way "
                + "I have of driving off the spleen, "
                + "and regulating the circulation. "
                + "Whenever I find myself growing grim about the mouth; "
                + "whenever it is a damp, drizzly November in my soul; "
                + "whenever I find myself involuntarily pausing before coffin "
                + "warehouses, and bringing up the rear of every funeral I meet; "
                + "and especially whenever my hypos get such an upper hand of me, "
                + "that it requires a strong moral principle to prevent me from "
                + "deliberately stepping into the street, "
                + "and methodically knocking people’s hats off - then, "
                + "I account it high time to get to sea as soon as I can. "
                + "This is my substitute for pistol and ball. "
                + "With a philosophical flourish Cato throws himself "
                + "upon his sword; I quietly take to the ship. "
                + "There is nothing surprising in this. If they but knew it, "
                + "almost all men in their degree, some time or other, "
                + "cherish very nearly the same "
                + "feelings towards the ocean with me.",
        "In the late summer of that year we lived in "
                + "a house in a village that looked across the river "
                + "and the plain to the mountains. "
                + "In the bed of the river there were pebbles and boulders, "
                + "dry and white in the sun, and the water was clear and swiftly "
                + "moving and blue in the channels. "
                + "Troops went by the house and down the road and "
                + "the dust they raised powdered the leaves of the trees. "
                + "The trunks of the trees too were dusty and the leaves fell "
                + "early that year and we saw the troops marching along the "
                + "road and the dust rising and leaves, stirred by the breeze, "
                + "falling and the soldiers marching and "
                + "afterward the road bare and white except for the leaves.",
        "It was the best of times, "
                + "it was the worst of times, "
                + "it was the age of wisdom, it was the age of foolishness, "
                + "it was the epoch of belief, it was the epoch of incredulity, "
                + "it was the season of Light, it was the season of Darkness, "
                + "it was the spring of hope, it was the winter of despair, "
                + "we had everything before us, we had nothing before us, "
                + "we were all going direct to Heaven, "
                + "we were all going direct the other way - "
                + "in short, the period was so far like the present period, "
                + "that some of its noisiest authorities insisted on its being "
                + "received, for good or for evil, "
                + "in the superlative degree of comparison only.",
        "I first met Dean not long "
                + "after my wife and I split up. "
                + "I had just gotten over a serious illness that "
                + "I won’t bother to talk about, except that "
                + "it had something to do with the miserably weary "
                + "split-up and my feeling that everything was dead. "
                + "With the coming of Dean Moriarty began the part "
                + "of my life you could call my life on the road. "
                + "Before that I’d often dreamed of going West to see the "
                + "country, always vaguely planning and never taking off. "
                + "Dean is the perfect guy for the road because he "
                + "actually was born on the road, "
                + "when his parents were passing through Salt Lake City in 1926, "
                + "in a jalopy, on their way to Los Angeles. "
                + "First reports of him came to me through Chad King, "
                + "who’d shown me a few letters from him written in a "
                + "New Mexico reform school. I was tremendously interested "
                + "in the letters because they so naively and sweetly asked "
                + "Chad to teach him all about Nietzsche and all the wonderful "
                + "intellectual things that Chad knew. At one point Carlo and "
                + "I talked about the letters and wondered if we would ever meet "
                + "the strange Dean Moriarty. This is all far back, "
                + "when Dean was not the way he is today, when he was a "
                + "young jailkid shrouded in mystery. Then news came that Dean "
                + "was out of reform school and was coming to New York for the "
                + "first time; also there was talk that he had just "
                + "married a girl called Marylou.",
        "Hale knew, before he had been in Brighton "
                + "three hours, that they meant to murder him. "
                + "With his inky fingers and his bitten nails, "
                + "his manner cynical and nervous, "
                + "anybody could tell he didn’t belong - "
                + "belong to the early summer sun, the cool "
                + "Whitsun wind off the sea, the holiday crowd. "
                + "They came in by train from Victoria every five minutes, "
                + "rocked down Queen’s Road standing on the "
                + "tops of the little local trams, stepped off "
                + "in bewildered multitudes into fresh and "
                + "glittering air: the new silver paint sparkled on the piers, "
                + "the cream houses ran away into the west like a "
                + "pale Victorian water-colour; a race in miniature motors, "
                + "a band playing, flower gardens in bloom below the "
                + "front, an aeroplane advertising something for "
                + "the health in pale vanishing clouds across the sky.",
        "It must have been around a quarter to eleven. "
                + "A sailor came in and ordered a chile dog and coffee. "
                + "I sliced a bun, jerked a frank out of the boiling water, "
                + "nested it, poured a half-dipper of chile over the frank "
                + "and sprinkled it liberally with chopped onions. "
                + "I scribbled a check and put it by his plate. "
                + "I wouldn’t have recommended the unpalatable mess "
                + "to a starving animal. The sailor was the only customer, "
                + "and after he ate his dog he left. "
                + "That was the exact moment she entered. "
                + "A small woman, hardly more than five feet. "
                + "She had the figure of a teenage girl. "
                + "Her suit was a blue tweed, smartly cut, "
                + "and over her thin shoulders she wore a fur jacket, "
                + "bolero length. Tiny gold circular earrings "
                + "clung to her small pierced ears. "
                + "Her hands and feet were small, "
                + "and when she seated herself at "
                + "the counter I noticed she wasn’t wearing any rings.",
        "It is a truth universally acknowledged, "
                + "that a single man in possession of a good fortune must be in "
                + "want of a wife. However little known the feelings or "
                + "views of such a man may be on his first entering a "
                + "neighbourhood, this truth is so well fixed in the minds of the "
                + "surrounding families, that he is considered as the rightful "
                + "property of some one or other of their daughters.",
        "Dark spruce forest frowned on either side of the "
                + "frozen waterway. The trees had been stripped by a "
                + "recent wind of their white covering of frost, "
                + "and they seemed to lean toward each other, "
                + "black and ominous, in the fading light. "
                + "A vast silence reigned over the land. "
                + "The land itself was a desolation, lifeless, "
                + "without movement, so lone and cold that the spirit of "
                + "it was not even that of sadness. "
                + "There was a hint in it of laughter, "
                + "but of a laughter more terrible than any sadness - "
                + "a laughter that was mirthless as the smile of the Sphinx, "
                + "a laughter cold as the frost and partaking of the "
                + "grimness of infallibility. "
                + "It was the masterful and incommunicable "
                + "wisdom of eternity laughing at the futility "
                + "of life and the effort of life. "
                + "It was the Wild, the savage, frozen-hearted Northland Wild.",
        "ABANDON ALL HOPE YE WHO ENTER HERE is "
                + "scrawled in blood red lettering on "
                + "the side of the Chemical Bank near the corner of "
                + "Eleventh and First and is in print large enough to be seen "
                + "from the backseat of the cab as it lurches forward in "
                + "the traffic leaving Wall Street and just as Timothy "
                + "Price notices the words a bus pulls up, "
                + "the advertisement for Les Miserables on its side blocking "
                + "his view, but Price who is with Pierce & Pierce "
                + "and twenty-six doesn't seem to care because he "
                + "tells the driver he will give him five dollars to turn "
                + "up the radio, \"Be My Baby\" on WYNN, "
                + "and the driver, black, not American, does so.",
        "I am a sick man. ... "
                + "I am a spiteful man. I am an unattractive man. "
                + "I believe my liver is diseased. However, "
                + "I know nothing at all about my disease, "
                + "and do not know for certain what ails me. "
                + "I don't consult a doctor for it, and never have, "
                + "though I have a respect for medicine and doctors. "
                + "Besides, I am extremely superstitious, "
                + "sufficiently so to respect medicine, anyway "
                + "(I am well-educated enough not to be superstitious, "
                + "but I am superstitious). No, "
                + "I refuse to consult a doctor from spite. "
                + "That you probably will not understand. "
                + "Well, I understand it, though. Of course, "
                + "I can't explain who it is precisely that "
                + "I am mortifying in this case by my spite: "
                + "I am perfectly well aware that I cannot \"pay "
                + "out\" the doctors by not consulting them; "
                + "I know better than anyone that by all this "
                + "I am only injuring myself and no one else. "
                + "But still, if I don't consult a doctor it is from spite. "
                + "My liver is bad, well then let it hurt even worse!",
        "No live organism can continue "
                + "for long to exist sanely under conditions of absolute "
                + "reality; even larks and katydids are supposed, by some, "
                + "to dream. Hill House, not sane, stood by itself against "
                + "its hills, holding darkness within; it had stood so for "
                + "eighty years and might stand for eighty more. "
                + "Within, walls continued upright, bricks met neatly, "
                + "floors were firm, and doors were sensibly shut; "
                + "silence lay steadily against the wood and "
                + "stone of Hill House, and whatever walked there, walked alone...",
        "As Gregor Samsa awoke one "
                + "morning from uneasy dreams he found himself transformed "
                + "in his bed into a gigantic insect. "
                + "He was lying on his hard, as it were armor-plated, "
                + "back and when he lifted his head a little he "
                + "could see his dome-like brown belly divided into "
                + "stiff arched segments on top of which the "
                + "bed quilt could hardly keep in position and "
                + "was about to slide off completely. "
                + "His numerous legs, which were pitifully thin "
                + "compared to the rest of his bulk, "
                + "waved helplessly before his eyes.",
        "I am an invisible man. "
                + "No, I am not a spook like those who haunted Edgar Allan Poe; "
                + "nor am I one of your Hollywood-movie ectoplasms. "
                + "I am a man of substance, of flesh and bone, fiber "
                + "and liquids-and I might even be said to possess a mind. "
                + "I am invisible, understand, simply because people "
                + "refuse to see me. Like the bodiless heads you see "
                + "sometimes in circus sideshows, it is as though "
                + "I have been surrounded by mirrors of hard, distorting glass. "
                + "When they approach me they see only my surroundings, "
                + "themselves, or figments of their imagination-"
                + "indeed, everything and anything except me.",
        "You don't know "
                + "about me without you have read a book by the "
                + "name of The Adventures of Tom Sawyer; "
                + "but that ain't no matter. That book was made "
                + "by Mr. Mark Twain, and he told the truth, mainly. "
                + "There was things which he stretched, "
                + "but mainly he told the truth. "
                + "That is nothing. I never seen anybody "
                + "but lied one time or another, without "
                + "it was Aunt Polly, or the widow, or "
                + "maybe Mary. Aunt Polly - Tom's Aunt Polly, "
                + "she is - and Mary, and the Widow Douglas is "
                + "all told about in that book, which is mostly a "
                + "true book, with some stretchers, as I said before."
    };

    public static String getBook(int index) {
        return bookContent[index];
    }
}
