@startuml
'https://plantuml.com/sequence-diagram

actor User

participant ":Parser" #LightGreen
User -> ":Parser" ++ #LightGreen: "add /uni 1"

participant ":Command" #Yellow
":Parser" -> ":Command" ++ #Yellow : addUniCommand(U: University)

participant ":Model" #Orange
":Command" -> ":Model" ++ #Orange: selectedUniversityList.addUniversity(U: University)
return
deactivate ":Model"

participant ":Storage" #LightGrey
":Command" -> ":Storage" ++ #LightGrey: updateSelectedUniversityList(selectedUniversityList: UniversityList)
return
deactivate ":Storage"

participant ":Ui" #DarkGrey
":Command" -> ":Ui" ++ #DarkGrey : printUniversity(U: University)
return
deactivate ":Ui"

":Command" --> ":Parser"
deactivate ":Command"

":Parser" --> User
deactivate ":Parser"


@enduml