@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam groupInheritance 2

ModuleStorage "1" ---* Storage
    ModuleStorage : + ArrayList<Module> readModuleList(InputStream inputStream);
    ModuleStorage : + String[] extractAttributes(String line);

UserStorage <|-- SelectedUniversityStorage
SelectedUniversityStorage "1" -----* Storage
    SelectedUniversityStorage : + updateFile(UniversityList universityList)
    SelectedUniversityStorage : + readFile(UniversityList universityMasterList, ModuleList moduleMasterList) : ArrayList<University>
    SelectedUniversityStorage : - updateMappings(ArrayList<ModuleMapping> moduleMappings, String line, ModuleList moduleMasterList, UniversityList universityMasterList, String universityName)
    SelectedUniversityStorage : - updateUniversityList(String universityName, ArrayList<ModuleMapping> moduleMappings, UniversityList universitySelectedList, UniversityList universityMasterList)
    SelectedUniversityStorage : - isMappingExist(ArrayList<ModuleMapping> mappings, ModuleMapping searchMapping) : boolean

UserStorage <|-- SelectedModuleStorage
SelectedModuleStorage "1" ------* Storage
     SelectedModuleStorage : + updateFile()
     SelectedModuleStorage : + readSelectedModuleList() : ArrayList<Module>

UniversityStorage "1" ---* Storage
    UniversityStorage : + readUniversityList() : ArrayList<University>
    UniversityStorage : + extractAttributes() : String[]
    UniversityStorage : + extractAttributes() : String[];

class UserStorage {
    # loadFile() : File;
}
class Storage {
    + readModuleList() : ArrayList<Module>
    + readUniversityList() : ArrayList<University>
    + readSelectedModuleList() : ArrayList<Module>
    + readSelectedUniversityList() : ArrayList<University>
    + updateSelectedModuleList()
    + updateSelectedUniversityList()
}
@enduml