@startuml
'https://plantuml.com/sequence-diagram

box "ui" #LightBlue
participant UiUniversity
participant Ui
end box

[-> UiUniversity: printUniversity(University U, boolean printMC)
activate UiUniversity

UiUniversity -> Ui: printIndex(int index, boolean println)
activate Ui

Ui -> Ui : stringPadder(int index, PaddingType INDEX)
activate Ui


Ui --> Ui
deactivate Ui

Ui --> UiUniversity
deactivate Ui



opt printMC
    UiUniversity -> Ui : stringPadder(String U.name, PaddingType UNIVERSITYNAME)
    activate Ui
    Ui --> UiUniversity
    deactivate Ui
   end

<-- UiUniversity
deactivate UiUniversity

@enduml