@startuml
!define ENTITY_COLOR_0 #FF4600
!define ENTITY_COLOR_1 #FF7100
!define ENTITY_COLOR_2 #FF9700
!define ENTITY_COLOR_3 #FFBE00
!define ENTITY_COLOR_4 #FFF400
!define ENTITY_COLOR_5 #B6F400
!define ENTITY_COLOR_6 #8CF400

!define ACTIVATION_COLOR_0 #FF8E66
!define ACTIVATION_COLOR_1 #FFAC6D
!define ACTIVATION_COLOR_2 #FFBF66
!define ACTIVATION_COLOR_3 #FFD366
!define ACTIVATION_COLOR_4 #FFF766
!define ACTIVATION_COLOR_5 #CDF260
!define ACTIVATION_COLOR_6 #B5F260

actor User as user ENTITY_COLOR_0
participant ":Ui" as ui ENTITY_COLOR_1
participant ":MedBot" as medbot ENTITY_COLOR_2
participant "<<Class>>\nParser" as parser ENTITY_COLOR_3
participant ":DeleteCommand" as command ENTITY_COLOR_4
participant "scheduler:Scheduler" as scheduler ENTITY_COLOR_5
participant "storage:Storage" as storage ENTITY_COLOR_6

autoactivate on
user -> ui ACTIVATION_COLOR_1: "delete 1"
ui -> medbot ACTIVATION_COLOR_2: "delete 1"
medbot -> parser ACTIVATION_COLOR_3: parseCommand("delete 1")

parser -> command **: DeleteCommand(1)
activate command ACTIVATION_COLOR_4
command --> parser
parser --> medbot
medbot -> command ACTIVATION_COLOR_4: execute()
command -> scheduler ACTIVATION_COLOR_5: deletePatient(1)
scheduler --> command

command --> medbot ACTIVATION_COLOR_1:
destroy command
medbot -> storage ACTIVATION_COLOR_6: saveData()
storage --> medbot
medbot --> ui
ui --> user



@enduml