@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

mainframe sd Add Goal Parsing

-> ":AddParser": parseAddGoalCommand\n(commandInstruction:String)
activate ":AddParser"

":AddParser" -> ":AddParser": getGoal(commandInstruction:String)
activate ":AddParser"
":AddParser" --> ":AddParser": goal: Goal
deactivate ":AddParser"

<-- ":AddParser": AddGoalCommand(goal)
deactivate ":AddParser"

@enduml