@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

-> ":AddHabitCommand": runCommand(goalList: GoalList, \nprintManager: PrintManager, storage: Storage)
activate ":AddHabitCommand"

":AddHabitCommand" -> "goalList:GoalList":addHabitToGoal(habit:Habit,\ngoalIndex,printManager)
activate "goalList:GoalList"

"goalList:GoalList" -> "goalList:GoalList": getGoal(goalIndex)
activate "goalList:GoalList"
"goalList:GoalList" --> "goalList:GoalList": goal: goal
deactivate "goalList:GoalList"

ref over "goalList:GoalList": Abstracted checks before\nadding Habit:\n1. Non-repeated Habit name.\n2. Interval for new Habit cannot \nexceed end date of goal.

"goalList:GoalList" -> "goalList:GoalList": updateHabitEndDate(goal, habit)
activate "goalList:GoalList"
"goalList:GoalList" --> "goalList:GoalList": newHabit: Habit
deactivate "goalList:GoalList"

"goalList:GoalList" -> "newHabit:Habit": populateIntervalsDuringHabitCreation()
activate "newHabit:Habit"
"newHabit:Habit" --> "goalList:GoalList"
deactivate "newHabit:Habit"

"goalList:GoalList" -> "goal:Goal": addHabit(newHabit)
activate "goal:Goal"
"goal:Goal" --> "goalList:GoalList"
deactivate "goal:Goal"

"goalList:GoalList" -> "printManager:PrintManager": printAddedHabit(newHabitName, goalDescription)
activate "printManager:PrintManager"
"printManager:PrintManager" --> "goalList:GoalList"
deactivate "printManager:PrintManager"

"goalList:GoalList" --> ":AddHabitCommand"
deactivate "goalList:GoalList"
<--":AddHabitCommand"
deactivate ":AddHabitCommand"


@enduml