@startuml
!include style.puml

autonumber

Actor User as user
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Data" as data DATA_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -> ui : "add -b m/1 a/500"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : parseCommand("add -b m/1 a/500")
activate logic LOGIC_COLOR

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml