@startuml

!include Style.puml

participant ": DeleteHabitCommand" as DeleteHabitCommand COMMAND_COLOUR
participant "goalList: GoalList" as goalList GOAL_COLOUR
participant "goal: Goal" as goal GOAL_COLOUR
participant "habitList: ArrayList<habit>" as habitList HABIT_COLOUR
participant "habit: Habit" as habit HABIT_COLOUR
participant "printManager: PrintManager" as printManager UI_COLOUR

-> DeleteHabitCommand: runCommand(\ngoalList: GoalList,\n printManager: PrintManager,\n storage: Storage)
activate DeleteHabitCommand

DeleteHabitCommand -> goalList: deleteHabitFromGoal(\ngoalIndex: int,\n habitIndex: int,\n printManager: PrintManager)
activate goalList

create goal
goalList -> goal: getGoal(goalIndex: int)
activate goal
goalList <-- goal

create habitList
goalList -> habitList
activate habitList
goal <- habitList: getHabitList()
goal --> habitList
goalList <-- habitList

create habit
goalList -> habit
activate habit
habitList <- habit: getHabit(\nhabitList: ArrayList<Habit>,\n habitIndex: int)
habitList --> habit: habit
goalList <-- habit


goalList -> goal: removeHabit(habitIndex: int)
goal -> goal: remove(habitIndex: int)
activate goal
goal --> goal
deactivate goal
goalList <-- goal


goalList -> goal: printRemovedHabit(\ngoal.getDescription(): String,\n habit.getHabitName(): String)
goal -> habit
habit -> printManager
activate printManager

return

return

@enduml