@startuml

!include Style.puml

-> ": DeleteHabitCommand": runCommand(\ngoalList: GoalList,\nprintManager: PrintManager,\nstorage: Storage)
activate ": DeleteHabitCommand"

": DeleteHabitCommand" -> "goalList: GoalList": deleteHabitFromGoal(\ngoalIndex: int,\nhabitIndex: int,\nprintManager: PrintManager)
activate "goalList: GoalList"

"goalList: GoalList" -> "goalList: GoalList": getGoal(goalIndex: int)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList": goal: Goal
deactivate "goalList: GoalList"

ref over "goalList: GoalList": Abstracted checks before\ndeleting Goal:\ngoalIndex is a positive integer \nand not out of bounds.

"goalList: GoalList" -> "goalList: GoalList": goal.getHabitList()
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList": habitList: ArrayList<habit>
deactivate "goalList: GoalList"

"goalList: GoalList" -> "goalList: GoalList": getHabit(\nhabitList: ArrayList<Habit>,\nhabitIndex: int)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList": habit: Habit
deactivate "goalList: GoalList"

ref over "goalList: GoalList": Abstracted checks before\nremoving Habit:\nhabitIndex is a positive integer \nand not out of bounds.


"goalList: GoalList" -> "goal: Goal": goal.removeHabit(habitIndex: int)
activate "goal: Goal"
return

"goalList: GoalList" -> "goalList: GoalList": printRemovedHabit(\ngoal.getDescription(): String,\nhabit.getHabitName(): String)
activate "goalList: GoalList"
"goalList: GoalList" -> ": PrintManager"
activate ": PrintManager"
return
"goalList: GoalList" --> "goalList: GoalList"
deactivate "goalList: GoalList"

return

return

@enduml