@startuml

!include Style.puml

-> ": DeleteGoalCommand": runCommand(\ngoalList: GoalList,\nprintManager: PrintManager,\nstorage: Storage)
activate ": DeleteGoalCommand"

": DeleteGoalCommand" -> "goalList: GoalList": deleteGoal(\ngoalIndex: int,\nprintManager: PrintManager)
activate "goalList: GoalList"

"goalList: GoalList" -> "goalList: GoalList": getGoal(goalIndex: int)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList"
deactivate "goalList: GoalList"

ref over "goalList: GoalList": Abstracted checks before\ndeleting Goal:\ngoalIndex  is a positive integer \nand not out of bounds.

"goalList: GoalList" -> "goalList: GoalList": updateChosenGoalIndex(\ngoalIndex: int)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList"
deactivate "goalList: GoalList"

"goalList: GoalList" -> "goalList: GoalList": remove(goal: Goal)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList"
deactivate "goalList: GoalList"


"goalList: GoalList" -> "goalList: GoalList": printRemovedGoal(\ngoal.getDescription(): String)
activate "goalList: GoalList"
"goalList: GoalList" -> ": PrintManager"
deactivate "goalList: GoalList"

activate ": PrintManager"
"goalList: GoalList" <-- ": PrintManager"
deactivate ": PrintManager"

return

return

@enduml