@startuml UpdateStockSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":DeleteDispense" as deletedispense COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant ":CommandSyntax" as commandsyntax COLOR_UTILITIES
    participant ":DispenseValidator" as dispensevalidator COLOR_UTILITIES
    participant ":Ui" as ui COLOR_UTILITIES
    participant ":Storage" as storage COLOR_UTILITIES
end box

box Inventory COLOR_INVENTORY_BOX
    participant ":Medicine" as medicine COLOR_INVENTORY
    participant ":Stock" as stock COLOR_INVENTORY
end box

autoactivate on
-> deletedispense: execute()
deletedispense -> ui: getInstance()
deletedispense <-- ui
deletedispense -> medicine : getInstance()
deletedispense <-- medicine

opt !isInvalidParameter
deletedispense -> commandsyntax : containsInvalidParameters()
deletedispense <-- commandsyntax : isInvalidParameter
    opt isValidDispenseId
    deletedispense -> dispensevalidator : isValidDispenseId()
    deletedispense <-- dispensevalidator : isValidDispenseId
    deletedispense -> deletedispense : setStockQuantity()
        loop medicines
            deletedispense -> deletedispense : medicine
            opt medicine intanceof Stock
                deletedispense -> stock : isDeleted()
                deletedispense <-- stock :
                opt stock.isDeleted
                    deletedispense -> stock : setDeleted()
                    deletedispense <-- stock : setAsDeleted

                    deletedispense -> stock : getStockID()
                    deletedispense <-- stock :
                    opt stock.getStockID() == stockIdToDispense
                    deletedispense -> stock : setQuantity()
                    deletedispense <-- stock :
                    end
                    deletedispense -->deletedispense
                end

            end
        end
    end
end
    deletedispense -> storage: getInstance()
    deletedispense <-- storage
    deletedispense -> storage: saveData()
    deactivate storage


@enduml