@startuml
'https://plantuml.com/sequence-diagram

autonumber

 -> Parser: parseCommand()
activate Parser

Parser -> DeleteExpiredIngredientsCommand: execute()
activate DeleteExpiredIngredientsCommand

DeleteExpiredIngredientsCommand -> IngredientRepository: deleteExpiredIngredients()
activate IngredientRepository

loop ingredientStorages


    loop ingredientStorageBatches

        alt batchExpiryDate < currentDate

            IngredientRepository -> expiryDatesToRemove: add(ingredientStorageBatch)
            activate expiryDatesToRemove

        end

    end

    expiryDatesToRemove -> IngredientRepository: expiryDatesToRemove
    deactivate expiryDatesToRemove

    loop expiryDatesToRemove

        IngredientRepository -> ingredientStorage: remove(expiryDate)
        activate ingredientStorage

        ingredientStorage --> IngredientRepository
        deactivate ingredientStorage

    end

end

IngredientRepository -> DeleteExpiredIngredientsCommand: Boolean
deactivate IngredientRepository

DeleteExpiredIngredientsCommand --> Parser: String
deactivate DeleteExpiredIngredientsCommand

<-- Parser: Command
deactivate Parser

@enduml