@startuml

!include Style.puml

-> ": DeleteGoalCommand": runCommand\n(goalList: GoalList,\n printManager: PrintManager,\n storage: Storage)
activate ": DeleteGoalCommand"

": DeleteGoalCommand" -> "goalList: GoalList": deleteGoal\n(goalIndex: int,\n printManager: PrintManager)
activate "goalList: GoalList"

create "goal: Goal"
"goalList: GoalList" -> "goal: Goal": getGoal(goalIndex: int)
activate "goal: Goal"
"goalList: GoalList" <-- "goal: Goal"


"goalList: GoalList" -> "goalList: GoalList": updateChosenGoalIndex\n(goalIndex: int)
activate "goalList: GoalList"
deactivate "goalList: GoalList"

"goalList: GoalList" -> "goalList: GoalList": remove(goal: Goal)
activate "goalList: GoalList"
deactivate "goalList: GoalList"

"goalList: GoalList" -> "goal: Goal": printRemovedGoal\n(goal.getDescription(): String)

"goal: Goal" -> ": PrintManager"
activate ": PrintManager"
deactivate ": PrintManager"

@enduml