@startuml
hide footbox
'https://plantuml.com/sequence-diagram
-> ":DeleteContactCommand": execute()
activate ":DeleteContactCommand"
alt#gold #lightgreen delete all contacts
    ref over ":DeleteContactCommand", ":DeleteContactCommand" :delete all contacts

else #lightblue delete selected contact
    ref over ":DeleteContactCommand", ":DeleteContactCommand" :delete selected contact
end

deactivate ":DeleteContactCommand"

@enduml