@startuml
hide footbox
'https://plantuml.com/sequence-diagram

-> ":EditContactCommand": execute()
activate ":EditContactCommand"

alt#gold #lightgreen PERSONAL_CONTACT_INDEX
    ref over ":EditContactCommand", ":EditContactCommand" :edit personal contact

else #lightblue ALL_CONTACTS_INDEX
    ":EditContactCommand" -> ":ExceptionTextUi":numOutOfRangeEditMessage(contactListSize:int)
    activate ":ExceptionTextUi"
    ":ExceptionTextUi" --> ":EditContactCommand":
    deactivate ":ExceptionTextUi"

else #gold CONTACT_INDEX
   ref over ":EditContactCommand", ":EditContactCommand" :edit contact
end


@enduml