@startuml
!include style.puml

Participant ":Parser" as parser PARSER_COLOUR
Participant ":FindCommand" as find COMMAND_COLOUR


-> parser : "find [keywords]"
activate parser PARSER_COLOUR

parser -> parser : parseAndRunFindCommand("find [keywords]")
activate parser PARSER_COLOUR_S1

loop all keywords entered
  parser -> find **: FindCommand(keyword)
  activate find COMMAND_COLOUR

  find --> parser
  deactivate find

  parser -> find : run()
  activate find COMMAND_COLOUR

  find --> parser : results for keyword
  deactivate find
end

parser --> parser : results for all keywords
deactivate parser

<-- parser : results for all keywords
deactivate parser

@enduml