@startuml
'https://plantuml.com/class-diagram
' hide the circles in the diagram
hide circle
' hide the icons for access modifiers
skinparam classAttributeIconSize 0
' to join all the arrows
skinparam groupInheritance 3

class "{abstract}\nMedicine"{
    #medicineName: String
    #quantity: int
    -{static} medicines: ArrayList<Medicine>
    +{static} getInstance()
    +Medicine(medicineName: String, quantity: int)
    +toFileFormat()
}

class "Stock"{
    -{static} stockCount: int
    #stockID: int
    #price: double
    #expiry: Date
    #description: String
    #maxQuantity: int
    #isDeleted: boolean
    +Stock(name: String, price: Double, quantity: int,
     expiry: Date, description: String, maxQuantity: int)
    +toFileFormat(): void
}

class "Dispense"{
    -{static} dispenseCount: int
    #dispenseId: int
    #customerId: int
    #date: Date
    #staff: String
    #stockId: int
    +Dispense(medicineName: String, quantity: int,
     customerId: String, date: Date, staff: String, stockId: int)
    +toFileFormat(): void
}

class "Order"{
    -{static} orderCount: int
    #orderId: int
    #date: Date
    #isDelivered: boolean
    +Order(medicineName: String,
    quantity: int, date: Date)
    +toFileFormat(): void
}

"{abstract}\nMedicine" <|-- "Stock"
"{abstract}\nMedicine" <|-- "Dispense"
"{abstract}\nMedicine" <|-- "Order"

note "Note: All the getter and setters are\nleft out in this diagram." as n1
@enduml