@startuml
!include Style.puml
hide circle
skinparam classAttributeIconSize 0

class Lesson MODEL_COLOR
class LessonList MODEL_COLOR

LessonList -[MODEL_COLOR_T1]> "*" Lesson : lessonList

package "AddLessonCommand" <<Rectangle>> {
}

package "DeleteLessonCommand" <<Rectangle>> {
}

package "FindLessonCommand" <<Rectangle>> {
}

package "ListLessonCommand" <<Rectangle>> {
}

AddLessonCommand .down[MODEL_COLOR_T1].> Lesson
AddLessonCommand .down[MODEL_COLOR_T1].> LessonList
DeleteLessonCommand .down[MODEL_COLOR_T1].>Lesson
DeleteLessonCommand .down[MODEL_COLOR_T1].> LessonList
FindLessonCommand .up[MODEL_COLOR_T1].> Lesson
FindLessonCommand .up[MODEL_COLOR_T1].> LessonList
ListLessonCommand .up[MODEL_COLOR_T1].> Lesson
ListLessonCommand .up[MODEL_COLOR_T1].> LessonList

@enduml
