@startuml
hide circle
skinparam classAttributeIconSize 0

class Lesson
class LessonList

LessonList -> "*" Lesson : lessonList

hide members

class AddLessonCommand
class DeleteLessonCommand
class FindLessonCommand
class ListLessonCommand
AddLessonCommand ..> Lesson
AddLessonCommand ..> LessonList
DeleteLessonCommand ..>Lesson
DeleteLessonCommand ..> LessonList
FindLessonCommand ..> Lesson
FindLessonCommand ..> LessonList
ListLessonCommand ..> Lesson
ListLessonCommand ..> LessonList

@enduml
