@startuml
!include Style.puml

participant ":ListGoalsCommand" as ListGoalsCommand COMMAND_COLOUR
participant "goalList:GoalList" as goalList GOAL_COLOUR
participant "printManager:PrintManager" as printManager UI_COLOUR

-> ListGoalsCommand: runCommand(goalList:GoalList,\nprintManager:printManager, storage:Storage)
activate ListGoalsCommand

ListGoalsCommand -> goalList:  listGoals(printManager)
activate goalList
alt#gold #lightblue goalList.size == 0
    goalList -> ":HabitCommandException": HabitCommandException\n(message:String)
    activate ":HabitCommandException"
    ":HabitCommandException" --> goalList
    deactivate ":HabitCommandException"

else #lightgreen else
    goalList -> printManager: printGoalList(goalList:ArrayList<Goal>,\ngoalList.size:int)
    activate printManager
    printManager --> goalList
    deactivate printManager
end

goalList --> ListGoalsCommand
deactivate goalList

<-- ListGoalsCommand
deactivate ListGoalsCommand

@enduml