@startuml

!include Style.puml

participant ": ListGoalParser" as ListGoalParser PARSER_COLOUR
participant ": ListGoalsCommand" as ListGoalsCommand COMMAND_COLOUR

mainframe sd List Goal Parsing

-> ListGoalParser: parseListGoalsCommand(input: String)
activate ListGoalParser
create ListGoalsCommand
ListGoalParser -> ListGoalsCommand: input
activate ListGoalsCommand

return

return new ListGoalCommand(input)




@enduml