@startuml
'https://plantuml.com/sequence-diagram

autonumber
 -> Parser: parseCommand()
activate Parser
Parser -> ListIngredientsExpiredCommand: execute()
activate ListIngredientsExpiredCommand
ListIngredientsExpiredCommand -> ingredientRepository: findExpiredIngredients()
activate ingredientRepository
ingredientRepository -> ingredientRepository: values()

ingredientRepository -> ingredientStorage: getIngredient()
activate ingredientStorage
ingredientStorage -> ingredientRepository: ingredient: Ingredient

 ingredientRepository -> expiredIngredientStorageIngredientStorage: new IngredientStorage(ingredient)
 activate expiredIngredientStorage
 expiredIngredientStorage -> ingredientRepository: expiredIngredientStorage



'    loop ingredientRepository.size
'        activate ingredientRepository
'        ingredientRepository -> ingredientStorage: values()
'        activate ingredientStorage
'        ingredientStorage -> Ingredient: toString()
'        activate Ingredient
'
'        Ingredient --> ingredientStorage: String
'        deactivate Ingredient
'        ingredientStorage --> ingredientRepository: String
'        deactivate ingredientStorage
'    end
'ingredientRepository --> ListIngredientsExpiredCommand: String
'deactivate ingredientRepository
'ListIngredientsExpiredCommand --> Parser: String
'deactivate ListIngredientsExpiredCommand
'<-- Parser: Command
'deactivate Parser
@enduml