@startuml AddSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":List*Command" as list COLOR_COMMAND
    participant ":CommandSyntax" as commandSyntax COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant ":Ui" as ui COLOR_UTILITIES
    participant ":*Validator" as validator COLOR_UTILITIES
    participant ":*Comparator" as comparator COLOR_UTILITIES
end box

box Inventory COLOR_INVENTORY_BOX
    participant ":Medicine" as medicine COLOR_INVENTORY
end box

autoactivate on

-> list: execute()
list -> ui : getInstance()
list <-- ui
list -> commandSyntax : containsInvalidParameters()
list <-- commandSyntax : isInvalidParameter

opt !isInvalidParameter
    list -> medicine : getInstance()
    list <-- medicine
    list -> validator : containsInvalidParameterValues()
    list <-- validator : isInvalidParameterValues

    opt !isInvalidParameterValues
        list -> list : filter*()

        alt SORT
            create comparator
            list -> comparator : new *Comparator()
            list <-- comparator : sorted*
            deactivate comparator
        else REVERSED SORT
            create comparator
            list -> comparator : new *Comparator()
            list <-- comparator : reverseSorted*
            deactivate comparator
        end
        list --> list : filtered*

        list -> ui : print*()
        deactivate ui
    end

end


@enduml