@startuml AddSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box MediVault COLOR_MEDIVAULT_BOX
    participant ": MediVault" as medivault COLOR_MEDIVAULT
end box

box Storage COLOR_STORAGE_BOX
    participant ": Storage" as storage COLOR_STORAGE
end box

box Ui COLOR_UI_BOX
    participant ": Ui" as ui COLOR_UI
end box

box Parser COLOR_PARSER_BOX
    participant ": CommandParser" as commandparser COLOR_PARSER
end box

box Command COLOR_COMMAND_BOX
    participant ": Command" as command COLOR_COMMAND
end box

autoactivate on

-> medivault: create
    medivault -> storage : getInstance()
    medivault <-- storage
    medivault -> storage : loadData()
    medivault <-- storage

    medivault -> medivault : run
    medivault -> ui : getInstance()
    medivault <-- ui
        loop until exit is received
            medivault -> ui : getInput()
            medivault <-- ui : userInput
            medivault -> commandparser : parseCommand(userInput : String)
            medivault <-- commandparser : userCommand, parameters
            medivault -> commandparser : processCommand()
            commandparser -> commandparser : parseParameters()
            commandparser --> commandparser : parameterValues
            create command
            commandparser -> command : Command(parametersValues : LinkedHashMap<String, String>)
            commandparser <-- command : command
            medivault <-- commandparser : command
            medivault -> command : execute()
            deactivate command
        end
note right of command
Note that Command throws
InvalidCommand to MediVault
when an invalid command is
entered.
end note

@enduml