@startuml
hide Circle
skinparam classAttributeIconSize 0

class Module
class ModuleList
class FullModuleList

ModuleList -down-> "*" Module : moduleList
FullModuleList -> "*" Module : fullModuleList
FullModuleList -> "*" Module : moduleMap

hide members

class AddModuleCommand
AddModuleCommand ..> Module
AddModuleCommand ..> ModuleList
AddModuleCommand ..> FullModuleList
@enduml
