@startuml
!include Style.puml

class Module MODEL_COLOR
class ModuleList MODEL_COLOR
class FullModuleList MODEL_COLOR

ModuleList -down-> "*" Module : moduleList
FullModuleList -> "*" Module : fullModuleList
FullModuleList -> "*" Module : moduleMap

hide members

class AddModuleCommand LOGIC_COLOR
AddModuleCommand ..> Module
AddModuleCommand ..> ModuleList
AddModuleCommand ..> FullModuleList
@enduml
