@startuml
hide circle
skinparam classAttributeIconSize 0

abstract class Command #pink {
+ {abstract} run() : String
}

class Parser #F3722C {
- {static} parseXYZCommand(command : String) : String
}

class XYZCommand #orchid {
+ run() : String
}

XYZCommand --|> Command
Parser "executes" --> XYZCommand

@enduml