@startuml AddSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":ReceiveOrderCommand" as receiveordercommand COLOR_COMMAND
    participant ":AddStockCommand" as addstockcommand COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant ":StockValidator" as stockvalidator COLOR_UTILITIES
end box

autoactivate on

mainFrame sd Logic for ReceiveOrderCommand

activate receiveordercommand
receiveordercommand -> receiveordercommand : isStockParametersValid(ui: Ui, medicines: ArrayList<Medicines>, name: String)
receiveordercommand -> stockvalidator : new StockValidator()
receiveordercommand <-- stockvalidator

receiveordercommand -> receiveordercommand : checkStockExist
receiveordercommand --> receiveordercommand
receiveordercommand -> stockvalidator : containsInvalidParametersAndValues(ui: Ui, medicines: ArrayList<Medicine>,\nparameters: LinkedHashMap<String, String>, requiredParameters: String[],\noptionalParameters: String[], commandSyntax: String,\nrequiresOptionalParameters: boolean, validator: MedicineValidator)
receiveordercommand <-- stockvalidator : isInvalidInput

receiveordercommand --> receiveordercommand
create addstockcommand
receiveordercommand -> addstockcommand : new AddStockCommand(parameters: LinkedHashMap<String, String>)
receiveordercommand <-- addstockcommand
receiveordercommand -> addstockcommand : execute()
deactivate addstockcommand



@enduml