@startuml AddSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":ReceiveOrderCommand" as receiveordercommand COLOR_COMMAND
    participant ":AddStockCommand" as addstockcommand COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant ":StockValidator" as stockvalidator COLOR_UTILITIES
end box

autoactivate on

mainFrame sd Logic for ReceiveOrderCommand

activate receiveordercommand
receiveordercommand -> receiveordercommand : isStockParametersValid()
receiveordercommand -> stockvalidator : new StockValidator()
receiveordercommand <-- stockvalidator

receiveordercommand -> receiveordercommand : checkStockExist
receiveordercommand --> receiveordercommand
receiveordercommand -> stockvalidator : containsInvalidParameters()
receiveordercommand <-- stockvalidator : isInvalidParameter

opt !isInvalidParameter
    receiveordercommand -> stockvalidator : containsInvalidParameterValues()
    receiveordercommand <-- stockvalidator : isInvalidParameterValues
    receiveordercommand --> receiveordercommand
    receiveordercommand -> addstockcommand : execute()
    deactivate addstockcommand
end




@enduml