@startuml
hide footbox
'https://plantuml.com/sequence-diagram

-> ":MainParser": execute()
activate ":MainParser"

":MainParser" -> ":MainParser" :getCommandWord(userInput:String)
activate ":MainParser"
":MainParser" -> ":SearchContactParser" :parseSearchQuery(userInput:String)
activate ":SearchContactParser"

":SearchContactParser" -> ":SearchContactParser" :parseSearchQuery(userInput:String)
activate ":SearchContactParser"
":SearchContactParser" --> ":SearchContactParser" :searchInput:String
deactivate ":SearchContactParser"

":SearchContactParser" -> ":SearchContactParser" :getDetailFlag(searchInput:String))
activate ":SearchContactParser"
":SearchContactParser" --> ":SearchContactParser" :detailFlag:int
deactivate ":SearchContactParser"

":SearchContactParser" -> ":SearchContactParser" :parseSearchQuery(searchInput:String)
activate ":SearchContactParser"
":SearchContactParser" --> ":SearchContactParser" :query:String
deactivate ":SearchContactParser"


":SearchContactParser" --> ":MainParser" : SearchContactCommand(query:String, detailFlag:int)
deactivate ":SearchContactParser"

":MainParser" -> ":SearchContactCommand" : SearchContactCommand:Command
activate ":SearchContactCommand"

":SearchContactCommand" -> ":ContactList" : searchContact(query:String, detailFlag:int)
activate ":ContactList"

loop for all contacts
":ContactList" -> ":ContactList" :getDetailFlag(userInput:String)
loop#gold #lightgreen for all contacts
    alt contact.getName().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end

    else GITHUB_INDEX
    alt contact.getGithub().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end

    else LINKEDIN_INDEX
    alt contact.getLinkedIn().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end

    else TELEGRAM_INDEX
    alt contact.getTelegram().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end
    else TWITTER_INDEX
    alt contact.getTwitter().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end
    else EMAIL_INDEX
    alt contact.getEmail().contains(query)
    ":ContactList" -> ":TextUI" : viewContactMessage(contact, i)
    activate ":TextUI"
    deactivate ":TextUI"
    end end
end

":ContactList"-->":SearchContactCommand"
deactivate ":ContactList"

":SearchContactCommand"-->":MainParser"
deactivate ":SearchContactCommand"
deactivate ":MainParser"


@enduml