@startuml
!include style.puml

box DUKE_COLOR
participant ":Duke" as Duke
end box
box BLUE_COLOR
participant ":Parser" as Parser
participant ":SelectParser" as SelectParser
end box


activate Duke
Duke -> Parser
activate Parser
Parser -> SelectParser
activate SelectParser

box LOGIC_COLOR
create ":SelectCommand" as SelectCommand
end box

SelectParser -> SelectCommand
activate SelectCommand

return
return
return

Duke -> SelectCommand: execute()
activate SelectCommand
    opt ItemType == EVENT

    end

    opt ItemType == TASK

    end
return :CommandResult

@enduml