@startuml
'https://plantuml.com/class-diagram
!include style.puml

hide circle
skinparam class {
              BorderThickness 1
              BorderColor #Black
          }

Package "Storage"<<RECTANGLE>> {
    class "Storage" #219EBC
    class "File" #219EBC
}

Storage -->"0..1" "File"

@enduml