!define COLOR_MEDIVAULT #1E90FF
!define COLOR_UTILITIES #FF8C00
!define COLOR_COMMAND #00FFFF
!define COLOR_ERRORS #DC143C
!define COLOR_INVENTORY #BA55D3
!define COLOR_SPARE #FF69B4
!define COLOR_SPARE1 #FFFF00
!define COLOR_SPARE3 #00FF00

!define COLOR_MEDIVAULT_BOX #ADD8E6
!define COLOR_UTILITIES_BOX #FAEBD7
!define COLOR_COMMAND_BOX #E0FFFF
!define COLOR_ERRORS_BOX #F08080
!define COLOR_INVENTORY_BOX #DDA0DD
!define COLOR_SPARE_BOX #FFC0CB
!define COLOR_SPARE1_BOX #FFFACD
!define COLOR_SPARE3_BOX #98FB98
