!define COLOR_MEDIVAULT #FFFAFA
!define COLOR_PARSER #F0FFF0
!define COLOR_COMMAND #F5FFFA
!define COLOR_UI #F0FFFF
!define COLOR_STORAGE #F0F8FF
!define COLOR_COMPARATORS #F8F8FF
!define COLOR_ERRORS #F5F5F5
!define COLOR_SPARE #FFF5EE

!define COLOR_MEDIVAULT_BOX #F5F5DC
!define COLOR_PARSER_BOX #FDF5E6
!define COLOR_COMMAND_BOX #FFDEAD
!define COLOR_UI_BOX #FFFAF0
!define COLOR_STORAGE_BOX #FFFFF0
!define COLOR_COMPARATORS_BOX #FAEBD7
!define COLOR_ERRORS_BOX #FAF0E6