@startuml
hide circle
skinparam classAttributeIconSize 0

class Task
class TaskList

TaskList -> "*" Task : taskList

hide members

class AddTaskCommand
class DeleteTaskCommand
class DoneTaskCommand
class FindTaskCommand
class ListTaskCommand
AddTaskCommand ..> Task
AddTaskCommand ..> TaskList
DeleteTaskCommand ..>Task
DeleteTaskCommand ..> TaskList
DoneTaskCommand ..> Task
DoneTaskCommand ..> TaskList
FindTaskCommand ..> Task
FindTaskCommand ..> TaskList
ListTaskCommand ..> Task
ListTaskCommand ..> TaskList
@enduml
