@startuml
!include Style.puml
hide circle
skinparam classAttributeIconSize 0

class Task MODEL_COLOR
class TaskList MODEL_COLOR

TaskList -[MODEL_COLOR_T1]> "*" Task : taskList

package "AddTaskCommand" <<Rectangle>> {
}

package "DeleteTaskCommand" <<Rectangle>> {
}

package "DoneTaskCommand" <<Rectangle>> {
}

package "FindTaskCommand" <<Rectangle>> {
}

package "ListTaskCommand" <<Rectangle>> {
}

AddTaskCommand .down[MODEL_COLOR_T1].> Task
AddTaskCommand .down[MODEL_COLOR_T1].> TaskList
DeleteTaskCommand .down[MODEL_COLOR_T1].>Task
DeleteTaskCommand .down[MODEL_COLOR_T1].> TaskList
DoneTaskCommand .up[MODEL_COLOR_T1].> Task
DoneTaskCommand .up[MODEL_COLOR_T1].> TaskList
FindTaskCommand .up[MODEL_COLOR_T1].> Task
FindTaskCommand .up[MODEL_COLOR_T1].> TaskList
ListTaskCommand .up[MODEL_COLOR_T1].> Task
ListTaskCommand .up[MODEL_COLOR_T1].> TaskList
@enduml
