@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

-> ":UpdateHabitCommand": runCommand(goalList: GoalList,\nprintManager: PrintManager,\nstorage: Storage
activate ":UpdateHabitCommand"

":UpdateHabitCommand" -> "goalList: GoalList": updateHabitAttributes(goalIndex,\nhabitIndex, newHabitName,\nnewHabitInterval, updateAttributes,\nexcessAttributes, printManager)
activate "goalList: GoalList"

"goalList: GoalList" -> "printManager: PrintManager": printUpdateHabitMessageStart()

alt#gold #lightblue updateAttributes[0] == 1
"goalList: GoalList" -> "goalList: GoalList": updateHabitNameFromGoal(goalIndex,\nhabitIndex, newHabitName, printManager)
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList":
deactivate "goalList: GoalList"
end

alt#gold #lightblue updateAttributes[1] == 1
"goalList: GoalList" -> "goalList: GoalList": updateHabitIntervalFromGoal(goalIndex, \nhabitIndex, newHabitInterval, printManager);
activate "goalList: GoalList"
"goalList: GoalList" --> "goalList: GoalList":
deactivate "goalList: GoalList"
end

"goalList: GoalList" -> "printManager: PrintManager": printUpdateHabitMessageEnd\n(excessAttributes)

"goalList: GoalList" --> ":UpdateHabitCommand"
deactivate "goalList: GoalList"

<-- ":UpdateHabitCommand"
deactivate ":UpdateHabitCommand"

@enduml