@startuml UpdatePrescriptionSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":UpdatePrescription" as updateprescription COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant ":StockValidator" as stockvalidator COLOR_UTILITIES
    participant "<<class>>\n:PrescriptionManager" as prescriptionmanager COLOR_UTILITIES
end box

autoactivate on
mainFrame sd Logic for UpdatePrescriptionCommand
activate updateprescription
    updateprescription -> prescriptionmanager: extractDispenseObject()
    updateprescription <-- prescriptionmanager
    create stockvalidator
    updateprescription -> stockvalidator: new StockValidator()
    updateprescription <-- stockvalidator
    alt hasNameParam && hasQuantityParam
        updateprescription -> updateprescription: processGivenNameAndQuantity()
        updateprescription --> updateprescription: isSuccessfulUpdate
    else hasNameParam && !hasQuantityParam
        updateprescription -> updateprescription: processGivenName()
        updateprescription --> updateprescription: isSuccessfulUpdate
    else !hasNameParam && hasQuantityParam
        updateprescription -> updateprescription: processGivenQuantity()
        updateprescription --> updateprescription: isSuccessfulUpdate
    else containsParamOtherThanNameAndQuantity
        updateprescription -> updateprescription: processOtherFields()
        updateprescription --> updateprescription: isSuccessfulUpdate
    end

@enduml