@startuml UpdateStockSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":UpdateStockCommand" as updatestock COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant "<<class>>\n:StockManager" as stockmanager COLOR_UTILITIES
end box

autoactivate on
mainFrame sd Logic for UpdateStockCommand
activate updatestock
    updatestock -> stockmanager: extractStockObject(parameters: LinkedHashMap<String, String>,\nmedicines: ArrayList<Medicine>)
    updatestock <-- stockmanager: stock

    updatestock -> updatestock: processQuantityValues(ui: Ui, \nmedicines: ArrayList<Medicine>, stock: Stock)
    updatestock --> updatestock: isValidQuantityValues

    updatestock -> updatestock: processDateInput(ui: Ui, \nmedicines: ArrayList<Medicine>, stock: Stock)
    updatestock --> updatestock: isValidExpDate

    opt isValidQuantityValues && isValidExpDate
        updatestock -> stockmanager: getFilteredStocksByName(medicines: ArrayList<Medicine>,\nstockName: String)
        updatestock <-- stockmanager: oldFilteredStocks
        opt parameters contains name
            updatestock -> updatestock: addNewRowForUpdate(filteredStocks: ArrayList<Stock>,\nmedicines: ArrayList<Medicine>)
            deactivate updatestock
            updatestock -> updatestock: getNewStock(medicines: ArrayList<Medicine>,\nstock: Stock)
            deactivate updatestock
        end
        updatestock -> stockmanager: getFilteredStocksByName(medicines: ArrayList<Medicine>,\nstockName: String)
        updatestock <-- stockmanager: filteredStocks
        updatestock -> updatestock: setUpdatesByStockId(filteredStocks: ArrayList<Stock>,\nstock: Stock)
        deactivate updatestock
    end

@enduml