@startuml
!include style.puml

box DUKE_COLOR
Participant ":Duke" as Duke
end box
box UI_COLOR
Participant ":Ui" as Ui
end box
box BLUE_COLOR
Participant ":Parser" as Parser
Participant ":UpdateParser" as UpdateParser
end box
box LOGIC_COLOR
Participant ":UpdateCommand" as UpdateCommand
end box

activate Duke
-> Duke :runSlam()
Duke -> Parser : "Update [Event_Index]"
activate Parser
Parser -> UpdateParser: "[Event_Index]"

    loop Until UpdateParser obtains all necessary User Input
        activate UpdateParser
        UpdateParser -> Ui
        activate Ui
        opt Update Event
            Ui -> Duke : printUpdateEventDetails(event)
            Ui -> Duke : Ui :updateIntroMessage()
            |||
            Duke -> Ui :readInput()
            |||
            Ui -> UpdateParser
            |||
        end
        opt Update Task/Member
            Ui -> Duke : printTask(task)
            Ui -> Duke : updateTaskIntroMessage()
            |||
            Duke -> Ui :readInput()
            |||
            Ui -> UpdateParser
            |||

        end
        return
    end
UpdateParser -> UpdateCommand: UpdateCommand(updateDetails)
activate UpdateCommand
|||
return UpdateCommand
return UpdateCommand
return UpdateCommand
Duke -> UpdateCommand : execute()
activate UpdateCommand
|||
return : CommandResult


@enduml