@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml
mainframe sd Update Goal Parsing

-> ":UpdateParser": parseUpdateGoalCommands\n(commandInstruction: String)
activate ":UpdateParser"

":UpdateParser" -> ":Parser": splitInput\n(commandInstruction)
activate ":Parser"
":Parser" --> ":UpdateParser": parameters: ArrayList<String>
deactivate ":Parser"

":UpdateParser" -> ":UpdateParser": getUpdateGoalAttributes\n(parameters)
activate ":UpdateParser"
":UpdateParser" --> ":UpdateParser": updateAttributes: int[3]
deactivate ":UpdateParser"

alt#gold #lightblue isUpdateGoalName
":UpdateParser" -> ":Parser": getName(parameters)
activate ":Parser"
":Parser" --> ":UpdateParser": newGoalName: String
deactivate ":Parser"
end
alt#gold #lightblue isUpdateGoalType
":UpdateParser" -> ":Parser": getType(parameters)
activate ":Parser"
":Parser" --> ":UpdateParser": newGoalType: String
deactivate ":Parser"
end
alt#gold #lightblue isUpdateGoalEndDate
":UpdateParser" -> ":Parser": getDate(parameters)
activate ":Parser"
":Parser" --> ":UpdateParser": newGoalEndDate: String
deactivate ":Parser"
end

":UpdateParser" -> ":Parser": getIndex(parameters, "/g")
activate ":Parser"
":Parser" --> ":UpdateParser": goalIndex: int
deactivate ":Parser"

":UpdateParser" -> ":UpdateParser": getExcessGoalAttributes\n(parameters)
activate ":UpdateParser"
":UpdateParser" --> ":UpdateParser": excessAttributes:\nArrayList<String>
deactivate ":UpdateParser"

<-- ":UpdateParser": UpdateGoalCommand\n(goalIndex, newGoalName,\nnewGoalType, new GoalEndDate\nupdateAttributes, excessAttributes)
deactivate ":UpdateParser"

@enduml