@startuml UpdateStockSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box Command COLOR_COMMAND_BOX
    participant ":UpdateStockCommand" as updatestock COLOR_COMMAND
end box

box Utilities COLOR_UTILITIES_BOX
    participant "<<class>>\n:StockManager" as stockmanager COLOR_UTILITIES
end box

autoactivate on
mainFrame sd Logic for UpdateStockCommand
activate updatestock
    updatestock -> stockmanager: extractStockObject()
    updatestock <-- stockmanager: stock

    updatestock -> updatestock: processQuantityValues()
    updatestock --> updatestock: isValidQuantityValues

    updatestock -> updatestock: processDateInput()
    updatestock --> updatestock: isValidExpDate

    opt isValidQuantityValues && isValidExpDate
        updatestock -> stockmanager: getFilteredStocksByName()
        updatestock <-- stockmanager: oldFilteredStocks
        opt parameters contains name
            updatestock -> updatestock: addNewRowForUpdate()
            deactivate updatestock
            updatestock -> updatestock: getNewStock()
            deactivate updatestock
        end
        updatestock -> stockmanager: getFilteredStocksByName()
        updatestock <-- stockmanager: filteredStocks
        updatestock -> updatestock: setUpdatesByStockId(stock)
        deactivate updatestock
    end

@enduml