@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> Parser: parseCommand()
activate Parser

Parser -> ViewIngredientCommand: execute()
activate ViewIngredientCommand

ViewIngredientCommand -> IngredientRepository: find(ingredientName: String)
activate IngredientRepository

IngredientRepository --> ViewIngredientCommand: ingredient: IngredientStorage
deactivate IngredientRepository

ViewIngredientCommand --> Parser: String
deactivate ViewIngredientCommand

<-- Parser: Command
deactivate Parser


@enduml