@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

participant ":Parser" as Parser
participant ":ViewIngredientCommand" as ViewIngredientCommand
participant ":IngredientRepository" as IngredientRepository

autonumber

-> Parser: parseCommand(userInput)
activate Parser

create ViewIngredientCommand
Parser -> ViewIngredientCommand: ViewIngredientCommand(ingredientName: String))
activate ViewIngredientCommand

return viewIngredientCommand
return command
destroy Parser

-> ViewIngredientCommand: execute()
activate ViewIngredientCommand

ViewIngredientCommand -> IngredientRepository: find(ingredientName: String)
activate IngredientRepository

IngredientRepository --> ViewIngredientCommand: ingredient: IngredientStorage
destroy IngredientRepository

<-- ViewIngredientCommand: ingredient
destroy ViewIngredientCommand


@enduml