@startuml

[-> SearchCommand : execute()
activate SearchCommand

alt Able to connect
    SearchCommand -> NusMods : searchModsOnline()
    activate NusMods
    NusMods -> NusMods : getOnlineModList()
    activate NusMods
    NusMods --> NusMods
    deactivate NusMods
    loop for each mod
            alt Module Code Match
                    NusMods -> NusMods : fetchModOnline()
                    activate NusMods
                    NusMods -> NusMods : getOnlineModInfo()
                    activate NusMods
                    NusMods --> NusMods
                    deactivate NusMods
                    NusMods -> ModStorage : saveModInfo()
                    activate ModStorage
                    ModStorage --> NusMods
                    deactivate ModStorage
                    NusMods -> ModStorage : loadModInfo()
                    activate ModStorage
                    ModStorage --> NusMods
                    deactivate ModStorage
                    deactivate NusMods
                alt All Flags Match
                    NusMods -> TextUI : PrintModBriefDescription()
                    activate TextUI
                    TextUI --> NusMods
                    deactivate TextUI
                else
                end
            else
            end
    end
    NusMods --> SearchCommand
    deactivate NusMods

else No connection or Quicksearch

    SearchCommand -> ModStorage : searchFiles()
    activate ModStorage
    loop for each json
        alt Module Code Match
            ModStorage -> ModStorage : loadModInfo()
            activate ModStorage
            ModStorage --> ModStorage
            deactivate ModStorage
            alt All Flags Match
                ModStorage -> TextUI : PrintModBriefDescription()
                activate TextUI
                TextUI --> ModStorage
                deactivate TextUI
            end
        end
    end
    ModStorage --> SearchCommand
    deactivate ModStorage

end

<-- SearchCommand
deactivate SearchCommand

@enduml