@startuml

-> WordGameCommand: run()
activate WordGameCommand
WordGameCommand -> WordGameCommand: getNumber(args, WORD_SIGNIFIER)
activate WordGameCommand
WordGameCommand --> WordGameCommand: wordLimit
deactivate

create WordLimitGame
WordGameCommand -> WordLimitGame: createGame(args, isReady, setContent)
activate WordLimitGame
WordLimitGame -> TextUi: getWordLimit()
activate TextUi
TextUi --> WordLimitGame: isValidWord(n)
deactivate
WordLimitGame --> WordGameCommand
deactivate

WordGameCommand -> WordLimitGame: runGame()
activate WordLimitGame
WordLimitGame -> WordLimitGame: trimContent(limit)
activate WordLimitGame
WordLimitGame --> WordLimitGame
deactivate
WordLimitGame -> WordLimitGame: getTimeNow()
activate WordLimitGame
WordLimitGame --> WordLimitGame
deactivate

loop until Exit
    WordLimitGame -> Utils: displayLines(row)
    activate Utils
    Utils --> WordLimitGame: line
    deactivate
    WordLimitGame -> TextUi: printLine(displayed)
    activate TextUi
    TextUi --> WordLimitGame
    deactivate
    WordLimitGame -> TextUi: readCommand()
            activate TextUi
            TextUi --> WordLimitGame: inputs
            deactivate
    alt Exit
    else continue typing
        WordLimitGame -> WordLimitGame: updateUserLines(inputs)
        activate WordLimitGame
    end
    deactivate
end

WordLimitGame --> WordGameCommand
deactivate
WordGameCommand -> WordLimitGame: gameSummary()
activate WordLimitGame

WordLimitGame -> WordLimitGame: getDuration()
activate WordLimitGame
WordLimitGame --> WordLimitGame: gameTime
deactivate

WordLimitGame -> TextUi: handleSummary(...,"Word-Limited")
activate TextUi
TextUi --> WordLimitGame: summary
deactivate
WordLimitGame -> WordLimitGame: handleStorage(summary)
activate WordLimitGame
WordLimitGame --> WordLimitGame
deactivate

WordLimitGame --> WordGameCommand
deactivate
destroy WordLimitGame

@enduml