@startuml
!include SequenceStyle.puml

Actor User as user
Participant ":Ui" as ui
Participant ":Taa" as taa
Participant "<<class>>\nParser" as parser
Participant ":AddStudentCommand" as addStudentCommand
Participant ":ModuleList" as moduleList
Participant ":Module" as module
Participant ":StudentList" as studentList
Participant ":Student" as student
Participant ":Storage" as storage

activate taa

taa -> ui : getUserInput()
activate ui

user -> ui : "add_student c/CS2113T\n i/a12345x n/jon geh"
ui --> taa : userInput:String
deactivate ui

taa -> parser : parseUserInput(userInput)
activate parser

create addStudentCommand
parser -> addStudentCommand
activate addStudentCommand
addStudentCommand -> parser
deactivate addStudentCommand

parser --> taa : command:addStudentCommand
deactivate parser

taa -> addStudentCommand : checkArguments()
activate addStudentCommand

addStudentCommand --> taa
deactivate addStudentCommand

taa -> addStudentCommand : execute(moduleList:ModuleList, ui:Ui, storage:Storage)
activate addStudentCommand

addStudentCommand -> moduleList : getModuleWithCode(moduleCode:String)
activate moduleList
moduleList --> addStudentCommand : module:Module
deactivate moduleList

addStudentCommand -> module : getStudentList()
activate module
module --> addStudentCommand : studentList:StudentList
deactivate module

addStudentCommand -> studentList : addStudent(Student student)
activate studentList
studentList --> addStudentCommand
deactivate studentList

addStudentCommand -> storage : save(moduleList:ModuleList)
activate storage
storage --> addStudentCommand
deactivate storage

addStudentCommand -> ui : printMessage("Student has been added ...")
activate ui
ui -> user : Display message:\n"Student has been added ..."
ui --> addStudentCommand
deactivate ui

deactivate addStudentCommand

@enduml