@startuml
!include SequenceStyle.puml

Actor User as user
Participant ":Taa" as taa
Participant ":SetMarkCommand" as setMarkCommand
Participant ":ClassList" as classList
Participant ":TeachingClass" as teachingClass
Participant ":AssessmentList" as assessmentList
Participant ":StudentList" as studentList
Participant ":Student" as student
Participant ":Storage" as storage

user -> taa : "set_marks c/CS2113T-F12 \ns/1 a/Midterms m/60"
activate taa

taa -> setMarkCommand : execute(classList:ClassList, \nui:Ui, storage:Storage)
activate setMarkCommand

setMarkCommand -> classList : getClassWithId("CS2113T-F12")
activate classList
classList --> setMarkCommand : teachingClass:TeachingClass
deactivate classList

alt teachingClass != null
setMarkCommand -> teachingClass : getStudentList()
activate teachingClass
teachingClass --> setMarkCommand : studentList:StudentList
deactivate teachingClass

setMarkCommand -> teachingClass : getAssessmentList()
activate teachingClass
teachingClass --> setMarkCommand : assessmentList:AssessmentList
deactivate teachingClass

setMarkCommand -> assessmentList : getAssessment("Midterms")
activate assessmentList
assessmentList --> setMarkCommand : assessment:Assessment
deactivate assessmentList

alt assessment != null
setMarkCommand -> studentList : getStudentAt(1)
activate studentList
studentList --> setMarkCommand : student:Student
deactivate studentList

alt student != null
setMarkCommand -> student : setMarks("Midterms", 60)
activate student
student --> setMarkCommand
deactivate student

setMarkCommand -> storage : save(classList)
activate storage
storage --> setMarkCommand
deactivate storage
end
end
end

setMarkCommand --> taa
deactivate setMarkCommand
taa -[hidden]-> setMarkCommand
destroy setMarkCommand

taa --> user
deactivate taa

@enduml