@startuml
'https://plantuml.com/sequence-diagram

Box

-> EditDishNameCommand: UserCommand
alt if exception
activate EditDishNameCommand
EditDishNameCommand -> FoodoramaException: throw new
activate FoodoramaException
FoodoramaException -> Ui: getExceptionMsg()
deactivate FoodoramaException
activate Ui
<- Ui : EXCEPTION_MSG
deactivate Ui

else else
EditDishNameCommand->DishList: editName(dishIndex)
deactivate EditDishNameCommand
activate DishList


DishList -> Ui: printAskNewNameDish(dishName)
activate Ui
<-Ui: INPUT_NEW_NAME_MSG
deactivate Ui

->DishList: newDishName
DishList -> Dish: setDishName(newDishName)
activate Dish
deactivate Dish
DishList -> Ui: printDishNameChanged(dishName, newName)
deactivate DishList
activate Ui
<- Ui: DISH_NAME_CHANGED_MSG
deactivate Ui

end





@enduml