@startuml
'https://plantuml.com/sequence-diagram

Box
-> Foodorama: Start of Program
activate Foodorama
Foodorama -> Storage: load()
activate Storage
Storage -> Storage : loadIngredients()
activate Storage#DarkSalmon
Storage -> IngredientList : ingredientList.add()
deactivate Storage#DarkSalmon
Storage -> Storage : loadDishes()
activate Storage#LightSalmon
Storage -> DishList : dishList.add()
deactivate Storage#LightSalmon
Storage -> Storage : loadFormat()
activate Storage#LightSalmon
deactivate Storage#LightSalmon
deactivate Foodorama

@enduml