@startuml

Actor User
User -> ":Click" : "module list"
participant ":Click"
":Click" -> ":Parser" : parseCommand()
participant ":Parser"
activate ":Parser"
create ":AddModuleCommand"
":Parser" -> ":AddModuleCommand" : new AddModuleCommand()
activate ":AddModuleCommand"
return
deactivate ":AddModuleCommand"
":Parser" -> ":Click" : AddModuleCommand
deactivate ":Parser"
":Click" -> ":AddModuleCommand" : execute()
activate ":AddModuleCommand"

opt no duplicate parameters
    ":AddModuleCommand" -> ":AddModuleCommand" : getModule()
    activate ":AddModuleCommand"
    ":AddModuleCommand" --> ":AddModuleCommand"
    deactivate ":AddModuleCommand"
    participant "<color red><<class>></color> \n ModuleManager"
    activate "<color red><<class>></color> \n ModuleManager"
    ":AddModuleCommand" -> "<color red><<class>></color> \n ModuleManager" : addNewModule(module)
    "<color red><<class>></color> \n ModuleManager" --> ":AddModuleCommand"
    deactivate "<color red><<class>></color> \n ModuleManager"
end

":AddModuleCommand" --> ":Click"
deactivate ":AddModuleCommand"

hide footbox
@enduml
