hide circle
hide empty members
skinparam classAttributeIconSize 0
skinparam groupInheritance 3

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle