package seedu.duke;
public enum Keyword {
    MEMBER_ENTRY, TRAINING_SCHEDULE_ENTRY, LIST_KEYWORD, NO_KEYWORD, EXIT_KEYWORD, ADD_MEMBER_KEYWORD,
    ADD_TRAINING_KEYWORD, DELETE_MEMBER_KEYWORD, DELETE_TRAINING_KEYWORD, FIND_KEYWORD
}