package seedu.duke;
public enum Keyword {
    MEMBER_ENTRY, TRAINING_SCHEDULE_ENTRY, LIST_MEMBER_KEYWORD,
    LIST_TRAINING_KEYWORD, NO_KEYWORD, EXIT_KEYWORD, ADD_MEMBER_KEYWORD,
    ADD_TRAINING_KEYWORD, DELETE_MEMBER_KEYWORD, DELETE_TRAINING_KEYWORD, FIND_TRAINING_KEYWORD, FIND_MEMBER_KEYWORD,
    EDIT_TRAINING_KEYWORD
}