package seedu.duke;

public enum Keyword {
    LIST_MEMBER_KEYWORD, LIST_TRAINING_KEYWORD, LIST_ATTENDANCE_KEYWORD,
    ADD_MEMBER_KEYWORD, ADD_TRAINING_KEYWORD, ADD_ATTENDANCE_KEYWORD,
    DELETE_MEMBER_KEYWORD, DELETE_TRAINING_KEYWORD, DELETE_ATTENDANCE_KEYWORD,
    FIND_MEMBER_KEYWORD, FIND_TRAINING_KEYWORD, EDIT_TRAINING_KEYWORD,
    EDIT_MEMBER_KEYWORD, NO_KEYWORD, EXIT_KEYWORD, HELP_KEYWORD
}
