@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide circle

TestCommand ..> GameEnvironment

GameEnvironment -> "1" Ui : "ui"
Ui <. GameEnvironment
GameEnvironment *--> "1" QuestionGenerator : "questionGenerator"
DifficultyModifier <. GameEnvironment
QuestionGenerator -> "1..*" Question : "questionBank"
note top on link 
  questionBank is stored as
  a Map<Double, Question>
  where Double is the weight
endnote
GameEnvironment ..>  Question

class TestCommand {
  + execute(ModuleManager moduleManager): void
}

class GameEnvironment {
  GameEnvironment(Ui ui, QuestionGenerator generator)
  + run(): void
  - showPreGameInformation(): void
  - promptQuestion(): Question
  - getUserFeedback(): int
  - updateQuestionDifficulty(Question question, int difficulty): void
  + {static} createNewEnvironment(List<Question> questions, int questionCount)
}

class QuestionGenerator {
  - random: Random
  - total: double
  - questionCount: int
  + QuestionGenerator(List<Question> questionBank, int questionCount)
  + QuestionGenerator(List<Question> questionBank, int questionCount, Random random)
  + hasNext(): boolean
  + next(): Question
  + getQuestionPoolSize(): int
  - addQuestion(Question question): void
}

class Question {
  - name
  - data
  - weight
  + Question(String question, String answer)
}

note bottom of Question
  The name and data represents
  question and answer respectively.
endnote

class Ui {
  + printSection(String... strings): void
  + getUserInput(String prompt): String
  + {static} getInstance(): Ui
}

class DifficultyModifier {
  + {static} tweakEasyQuestionDifficulty(double initial): double
  + {static} tweakHardQuestionDifficulty(double initial): double
  - {static} getCurveValue(double x): double
}


@enduml