@startuml
!include Style.puml
skinparam sequence {
ParticipantBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor peachpuff
}

skinparam sequenceArrowColor black

Gordon -> Parser: addRecipeParse
activate Parser

' Name
Parser -> Parser: parseName
activate Parser

Parser --> Parser
deactivate Parser

Parser -> Recipe**: <<create>>
activate Recipe

' Ingredients
Parser -> Parser: parseIngredients
activate Parser

loop for all ingredients
Parser -> Recipe: addIngredient
end

Parser --> Parser
deactivate Parser

' Steps
Parser -> Parser: parseSteps
activate Parser

loop for all steps
Parser -> Recipe: addStep
end

Parser --> Parser
deactivate Parser

Recipe --> Parser: r
deactivate Recipe
destroy Recipe

Parser --> Gordon: addCommand
deactivate Parser

@enduml