@startuml
skinparam classAttributeIconSize 0
hide circle
!includesub CommandClassDiagram.puml!COMMAND

abstract class  "{abstract}\nWorkspaceCommand" as WorkspaceCommand extends Command {
# commandMap: CommandParser
+ WorkSpaceCommand(commandMap: CommandParser)
+ execute(ui: Ui, moduleManager: ModuleManager): CommandResult
}

abstract class "{abstract}\nInnerModuleCommand" as InnerModuleCommand extends WorkspaceCommand {
- commandMap: InnerModuleCommandParser
+ InnerModuleCommand(commandMap: InnerModuleCommandParser)
+ execute(ui: Ui, moduleManager: ModuleManager): CommandResult
}

class GoCommand extends WorkspaceCommand {
- moduleName: String
+ parseArguments(arguments: String): void
+ execute(ui: Ui, moduleManager: ModuleManager): CommandResult
}
class ModuleCommand extends WorkspaceCommand

class NotesCommand extends InnerModuleCommand
class ScheduleCommand extends InnerModuleCommand
class QuestionCommand extends InnerModuleCommand
class XYZCommand extends Command

@enduml