@startuml
!include Style.puml
skinparam ArrowColor LOGIC_GREEN_4
left to right direction

rectangle "Command" {
    rectangle "{abstract}\nCommand" LOGIC_GREEN_1 {
    }

    rectangle "Basic Commands" {
        rectangle AddCommand LOGIC_GREEN_1 {
        }

        rectangle DeleteCommand LOGIC_GREEN_1 {
        }

        rectangle CheckCommand LOGIC_GREEN_1 {
        }

        rectangle ListRecipesCommand LOGIC_GREEN_1 {
        }

        rectangle HelpCommand LOGIC_GREEN_1 {
        }

        rectangle NullCommand LOGIC_GREEN_1 {
        }
    }

    Rectangle "Find Commands" {
        rectangle FindCaloriesCommand LOGIC_GREEN_1 {
        }

        rectangle FindDifficultyCommand LOGIC_GREEN_1 {
        }

        rectangle FindIngredientsCommand LOGIC_GREEN_1 {
        }

        rectangle FindPriceCommand LOGIC_GREEN_1 {
        }

        rectangle FindTagsCommand LOGIC_GREEN_1 {
        }
    }

    rectangle "Set Commands" {
        rectangle SetCaloriesCommand LOGIC_GREEN_1 {
        }

        rectangle SetDifficultyCommand LOGIC_GREEN_1 {
        }

        rectangle SetPriceCommand LOGIC_GREEN_1 {
        }
    }

    AddCommand --|> "{abstract}\nCommand"
    DeleteCommand --|> "{abstract}\nCommand"
    CheckCommand --|> "{abstract}\nCommand"
    ListRecipesCommand --|> "{abstract}\nCommand"
    HelpCommand --|> "{abstract}\nCommand"
    NullCommand --|> "{abstract}\nCommand"
    "{abstract}\nCommand" <|--- FindCaloriesCommand
    "{abstract}\nCommand" <|--- FindDifficultyCommand
    "{abstract}\nCommand" <|--- FindIngredientsCommand
    "{abstract}\nCommand" <|--- FindPriceCommand
    "{abstract}\nCommand" <|--- FindTagsCommand
    "{abstract}\nCommand" <|--- SetCaloriesCommand
    "{abstract}\nCommand" <|-- SetDifficultyCommand
    "{abstract}\nCommand" <|-- SetPriceCommand
}
@enduml