@startuml
'https://plantuml.com/sequence-diagram

activate Content
[-> Content: setContent()

alt Input = 0
    Content -> Books: setBooks()
    activate Books
    Books --> Content: getBook()
    deactivate Books

else Input = 1

    Content -> WikiImport: setWikipedia()
    activate WikiImport
    WikiImport --> Content: getArticle()
    deactivate WikiImport

else Input = 2

    Content -> RandomGenerator: setRandomContent()
    activate RandomGenerator
    RandomGenerator --> Content: randomString()
    deactivate RandomGenerator

end

<-- Content: getContent()

@enduml