@startuml
!include Style.puml
skinparam ArrowColor LOGIC_BLUE_5

hide empty fields
hide empty methods

rectangle "Util" {
    enum "<<enumeration>> \n Difficulty" LOGIC_PINK_1  {
            NONE
            EASY
            MEDIUM
            HARD
        }

    rectangle Tag LOGIC_PINK_1 {
    }
}

rectangle "Kitchen" {
    rectangle Cookbook LOGIC_BLUE_3 {
    }
    rectangle Recipe LOGIC_BLUE_3 {
    }

    Cookbook --> "<<enumeration>> \n Difficulty"
    Cookbook *- Recipe
    Cookbook *--- Tag
}
@enduml