@startuml
!include Style.puml
skinparam ArrowColor black
skinparam classBorderColor black

rectangle "Util" {
    enum "<<Enumeration>> \n Difficulty" LOGIC_YELLOW_1  {
        NONE
        EASY
        MEDIUM
        HARD
    }

    class Tag LOGIC_YELLOW_1
}

rectangle "Kitchen" {
    class Cookbook LOGIC_BLUE_1
    class Recipe LOGIC_BLUE_1

    Cookbook --> "<<Enumeration>> \n Difficulty"
    Cookbook *- "*" Recipe : contains >
    Cookbook *-right-- "*" Tag : contains >
}
@enduml