@startuml
!include style.puml

box "Main" #whitesmoke
participant ":Terminus" as Terminus #white
endbox
box "UI" #bisque
participant ":Ui" as Ui
endbox
box "Parser" #aquamarine
participant ":CommandParser" as CommandParser #palegreen
endbox
box "Command" #thistle
participant ":Command" as Command #violet
participant ":CommandResult" as CommandResult #violet
endbox
box "Storage" #lightpink
participant ":StorageManager" as StorageManager #mistyrose
endbox
autoactivate on

-> Terminus: run()
Terminus -> Terminus: initialize()
ref over Terminus,CommandParser: Initialization
return
  Terminus -> Terminus : runCommandsUntilExit()
    loop True
      Terminus -> Ui : requestCommand ()
      return String
      Terminus -> Terminus: handleUserInput(input)
        Terminus -> CommandParser: parseCommand(input)
        return Command
        Terminus -> Command : execute(moduleManager)
        create CommandResult
        Command -> CommandResult
        return CommandResult
     return CommandResult
   return CommandResult
      break commandResult.isExit() == true
        note over Terminus, CommandResult : Breaks out of loop and Returns runCommandsUntilExit()
      end
      Terminus -> Terminus: handleCommandResult(commandResult)
        alt commandResult.getNewCommandParser() != null
          Terminus -> CommandResult: getNewCommandParser()
          return CommandParser
          Terminus -> Ui:printParserBanner(parser, moduleManager)
          return
        else
          Terminus -> Ui:printSection(commandResult.getMessage())
          return
        end
      return
      Terminus -> Terminus: handleStorage(commandResult)
        opt commandResult.hasChange() == true
          Terminus -> StorageManager: executeCommandResult(moduleManager, commandResult)
          return
        end
        Terminus -> StorageManager: updateMainJsonFile(moduleManager)
        return
      return
      destroy CommandResult
    end
    return
        Terminus -> Terminus :exit()
        ref over Terminus,StorageManager: Exit
        return
    return
destroy Terminus
destroy Ui
destroy CommandParser
destroy Command
destroy StorageManager
@enduml