@startuml
'https://plantuml.com/sequence-diagram
!include SequenceStyle.puml
box "Main" TERMINUS_BOX_COLOR
participant ":Terminus" as Terminus TERMINUS_COLOR
endbox
box "Storage" STORAGE_BOX_COLOR
participant ":StorageManager" as StorageManager STORAGE_COLOR
endbox
box "Module" MODULE_BOX_COLOR
participant ":ModuleManager" as ModuleManager MODULE_COLOR
endbox

autoactivate on

mainframe sd Intialization

 -> Terminus: initialize()

    create StorageManager
    Terminus -> StorageManager : StorageManager(DATA_DIRECTORY, MAIN_JSON)
    return StorageManager
    Terminus -> StorageManager: initialize()
    return ModuleManager
    opt moduleManager == null
      create ModuleManager
      Terminus -> ModuleManager: ModuleManager()
      return ModuleManager
    end
  return

@enduml