@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
box "Main" #whitesmoke
participant ":Terminus" as Terminus #white
endbox
box "Storage" #lightpink
participant ":StorageManager" as StorageManager #mistyrose
endbox


autoactivate on

mainframe sd Exit

 -> Terminus: exit()
  Terminus -> StorageManager:setDisabled(false)
  return
  Terminus -> StorageManager:save(moduleManager);
  return
 return

@enduml