@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
box "Main" #whitesmoke
participant ":Terminus" as Terminus #white
endbox
box "Storage" #lightpink
participant ":StorageManager" as StorageManager #mistyrose
endbox
box "Module" #coral
participant ":ModuleManager" as ModuleManager #lightsalmon
endbox

autoactivate on

mainframe sd Intialization

 -> Terminus: initialize()

    create StorageManager
    Terminus -> StorageManager : StorageManager(DATA_DIRECTORY, MAIN_JSON)
    return StorageManager
    Terminus -> StorageManager: initialize()
    return ModuleManager
    opt moduleManager == null
      create ModuleManager
      Terminus -> ModuleManager: ModuleManager()
      return ModuleManager
    end
  return

@enduml