@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide circle

NusModule -> "1" ContentManager: noteManager
NusModule -> "1" ContentManager: linkManager
NusModule -> "1" ContentManager: questionManager

ModuleManager  --> "*" NusModule :  has >
!startsub MODULEMANAGER
class ModuleManager {
  + getAllModules(): String []
  + getModule(moduleName: String): NusModule
  + removeModule(moduleName: String): void
  + setModule(moduleName: String): void
}
!endsub

class NusModule {
  + getContentManager (type: Class<T>): ContentManager<T>
}

 !includesub Content.puml!CONTENTMANAGER

@enduml