@startuml
!includesub CommandClassDiagram.puml!COMMAND
skinparam classAttributeIconSize 0
hide circle
!startsub COMMANDPARSER
abstract class "{abstract}\nCommandParser" as CommandParser {
 - workplace: String
 + CommandParser(workspace: String)
 + {abstract} parseCommand(command: String): Command
 + getHelpMenu(): String[]
}
!endsub

class XYZCommandParser  {
- commandParser: XYZCommandParser
+ parseCommand(command: String): Command
+ {static} getInstance(): XYZCommandParser
}

class Terminus

CommandParser --> "2..*" Command: has >
Terminus -> "0..1" CommandParser: commandParser
XYZCommandParser --|>  CommandParser

@enduml