@startuml
!include Style.puml
skinparam ArrowColor black
skinparam classBorderColor black

class Gordon #white {
Gordon()
Run()
}

rectangle Util {
    class Parser {
    parseMaster()
    parseNextLine()
    }

    class Command {
    execute()
    }

    class UI {
    printIntro()
    printExitMessage()
    printHelp()
    }
}

rectangle exception {
    class GordonException LOGIC_PINK_1 {
    }
}

Gordon "1" -> "1" Parser : creates >
Parser --> Command : creates >
Parser --> UI : uses >
GordonException <-- Parser : creates <

@enduml