@startuml
'https://plantuml.com/class-diagram

Gordon --> Parser
Parser --> Command
Parser -> UI

class Gordon {
Parser parser
Gordon()
Run()
}

class Parser {
public static final int NAME_INDEX
public static final int INGREDIENTS_INDEX
public static final int STEPS_INDEX
public static final int CALORIES_INDEX
public static final int INGREDIENTS_WORD_LENGTH
public static final int STEPS_WORD_LENGTH
Parser()
parseMaster()
parseNextLine()
parseCommand()
parseName()
parseIngredients()
parseSteps()
parseCalories()
addRecipeParse()
deleteRecipeParse()
setParse()
findParse()
addTagParse()
deleteTagParse()
untagParse()
}

class Command {
}

class UI {
printIntro()
printExitMessage()
printHelp()
}
@enduml