@startuml
!include Style.puml
skinparam ArrowColor black
skinparam classBorderColor black

rectangle "Util" {
    class Command
}

rectangle "Kitchen" {
    class Cookbook LOGIC_BLUE_1
    class Recipe LOGIC_BLUE_1

    Recipe <-- Command : modifies <
    Cookbook <-- Command : modifies <
    Cookbook "1" *- "*" Recipe : contains >
@enduml