@startuml
'https://plantuml.com/class-diagram

!include ClassStyle.puml

class Terminus TERMINUS_COLOR{
  - moduleStorage: ModuleStorage
  + {static} main(args: String[]): void
  + run(): void
  - start(): void
  - runCommandsUntilExit(): void
  - handleIoException(): void
  - exit(): void
}

class Ui {
  - {static} UI: ui
  - scanner: Scanner
  + {static} getInstance(): Ui
  - Ui()
  + Ui(in: InputStream)
  + printParserBanner(parser: CommandParser, moduleManager: ModuleManager): void
  + requestCommand(workspaceName: String): String
  + printSection(strings: String[]): void
  + printExitMessage(): void
  + getUserInput(prompt: String): String
}

class GameEnvironment ACTIVERECALL_COLOR{
  - questionGenerator: QuestionGenerator
  + {static} createNewEnvironment(questions: List<Question>, questionCount: int)
  GameEnvironment(ui: Ui, generator: QuestionGenerator)
  + run(): void
  - showPreGameInformation(): void
  - promptQuestion(): Question
  - getUserFeedback(): int
  - updateQuestionDifficulty(question: Question: difficulty: int): void
}

Terminus -> "1" Ui
Ui "1" <-- GameEnvironment

@enduml