package medbot.command;

public enum CommandType {
    HELP, EXIT, SWITCH, ADD_PERSON, DELETE_PERSON, EDIT_PERSON, VIEW_PERSON, LIST_PERSON, FIND_PERSON,
    ADD_APPOINTMENT, DELETE_APPOINTMENT, EDIT_APPOINTMENT, LIST_APPOINTMENT, VIEW_APPOINTMENT
}
