title: "SEPlanner"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md
  - README.md
  
markdown: kramdown

repository: "/AY2122S1-CS2113T-T09-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji