@startuml
'https://plantuml.com/sequence-diagram
skinparam actorStyle awesome
Actor User as user #abcdef
Participant ":UI" as ui #abcdef
Participant ":Parser" as parser #f3f609
Participant ":Entry" as entry #f3f609
Participant ":Command" as command
Participant ":Member" as member #d83815
Participant ":Storage" as storage #ffffff

user -> ui : entry = "add /m Bob /s A01231234B /g M /p 98765432"

ui -> parser
activate parser

parser -> entry : waitForQuery()
activate entry

entry -> parser : getKeywordStatus(entry)

parser --> entry : keyword = ADD_MEMBER
deactivate entry

entry -> parser : getMemberDetails(entry)
activate entry
parser --> entry : member = new Member(Bob, A01231234B, M, 98765432)

entry -> command : new AddMember(memberList, member)
activate command

command -> member : members.addMember(member)
activate member

member -> storage : writeMemberFile(memberFile, members)
activate storage

storage -> storage : save to disk
activate storage

storage --> storage
deactivate storage

storage --> member
deactivate storage

member --> command
deactivate member

command --> entry
deactivate command

entry --> parser
deactivate entry

deactivate parser
@enduml