@startuml
'https://plantuml.com/use-case-diagram

skinparam actorStyle awesome

User -down-> (UI)
(UI) -down-> (Parser)
(Parser) -right-> (Training)
(Parser) -left-> (Members)
(Parser) -down-> (Attendance)
(Members) -down-> (Attendance)
(Training) -down-> (Attendance)
(UI) -[hidden]left- (MemberStorage)
(Members) <-up-> (MemberStorage) : Read/Write

@enduml