@startuml
'https://plantuml.com/component-diagram
skinparam classAttributeIconSize 0

Package Attendance <<Rectangle>> {
Class Attendance
Class AttendanceList
}

Package Member <<Rectangle>> {
Class Member
hide member
}

Package Training <<Rectangle>> {
Class TrainingSchedule
hide member
}

Package Storage <<Rectangle>> {
Class AttendanceStorage
hide member
}

Class Attendance {
# String memberName
# String trainingName
# String attended
# int index
}

Class AttendanceList {
-ArrayList<Attendance> AttendanceList
+addAttendance(): Attendance
+deleteAttendance(): Attendance
}

AttendanceStorage "1"..>"1" AttendanceList
AttendanceList ..> "*" Attendance
Attendance *-left- "1" Member
Attendance *-right- "1" TrainingSchedule

hide circle
@enduml