@startuml
'https://plantuml.com/component-diagram


Package Member <<Rectangle>> {

Class MemberList
Class Member
}

Package Storage <<Rectangle>> {
Class MemberStorage
}

MemberStorage ..>   "1"MemberList
MemberList "1"..>"*" Member

hide members
hide circle
@enduml
